In [ ]:
rolehta <- c(1, 2.3, 5, 9, 10, 45, 4+2, 2/3, 8^2)

In [ ]:
rolehta

In [ ]:
rolehta[2]

In [ ]:
compras <- c("salsinha", "ovo", "leite", "azeite", "tubaína", "camisa do curintia", "pão", "café")

In [ ]:
compras

In [ ]:
compras[3]

In [ ]:
compras[c(3,7)]

In [ ]:
10:1

In [ ]:
compras

In [ ]:
compras[2:5]

In [ ]:
compras[c(2:4,6:8)]

In [ ]:
1:4 == c(1,2,3,4)

In [ ]:
v <- 11:20
v
# Fatiando v
# Quero os três primeiros elementos. Como faço?
v[1:3]

`length(v)` calcula o comprimento (quantidade de elementos) do vetor `v`.

In [ ]:
v <- 11:20
length(v)

In [ ]:
compras

In [ ]:
length(compras)

In [ ]:
v

In [ ]:
# E os três últimos?
v[-3:-1]
# Sinal de menos _exclui_ elementos
#v[-(1:3)]

In [ ]:
v[-2:-1]

In [ ]:
v <- 0:100000

In [ ]:
v

In [ ]:
n <- length(v)
n
(n-2):n
v[(n-2):n]

In [ ]:
v <- 11:20
length(v)
v[11]

In [ ]:
c(2,3,5,7)

In [ ]:
v

In [ ]:
v[2]

In [ ]:
v[c(2,3,5,7)]

In [ ]:
# vai dar erro
v[2,3,5,7]

In [ ]:
10:1

In [ ]:
# Em ordem invertida?
v[10:1]

In [ ]:
# Os de índice 3, 1, 4, 1, 5, 9, 2, nessa ordem?
v[c(3,1,4,1,5,9,2)]

## Posso colocar nomes nos índices?
Sim! Use a função `names(v)` para nomear os índices!

In [ ]:
ends <- c("Vergueiro, 1951", "Apeninos, 960", "Vergueiro, 1549")
ends

In [ ]:
ends[3]

In [ ]:
names(ends)

In [ ]:
names(ends) <- c("Ana Rosa", "Paraíso 1", "Paraíso 2")
ends

In [ ]:
ends[1]

In [ ]:
ends["Ana Rosa"]

In [ ]:
ends[c("Paraíso 1", "Paraíso 2")]

In [ ]:
v <- c(1,2,3)
names(v) <- c("um", "dois", "três")
v

In [ ]:
w <- c("um", "dois", "três")
names(w) <- 1:3
w

In [ ]:
w["1"]

In [ ]:
class(v)  # class só considera conteúdo, não nomes

# Coerção
Vimos que não podemos misturar objetos de classes diferentes em um mesmo vetor. Na hora de misturar:
* `logical` com `numeric`: vira tudo `numeric`
* `numeric` com `character`: vira tudo `character`
* e se tiver `logical` com `character`?

In [ ]:
u <- c(TRUE, FALSE, TRUE, TRUE)
u
class(u)

In [ ]:
v <- c(TRUE, 30, FALSE, 40)
v
class(v)

In [ ]:
v2 <- c("dois", 3, 4)
v2
class(v2)

In [ ]:
v2[2]
v2[3]

In [ ]:
# Vai dar erro, pois '3' e '4' são textos, e não números
v2[2]+v2[3]

In [ ]:
v3 <- c(TRUE, FALSE, 0, "texto")
v3

In [ ]:
-TRUE

In [ ]:
# Vai dar erro pois 'TRUE' e 'FALSE' são textos, e não lógicos
v3[1] & v3[2]

# Contas com vetores
O que acontece se a gente usar as operações nos vetores?

In [ ]:
salarios <- c(10000, 12000, 9000, 8500, 12000, 11000)
salarios

In [ ]:
salarios
salarios + 1000

In [ ]:
salarios*1.10

`1e+07`: $1\cdot 10^{+07}$

`1.2e+07`: $1.2\cdot 10^{+07}$

In [ ]:
salarios
salarios+salarios*0.1

In [ ]:
aumentos <- c(1000, 500, 800, 1200, 1000, 800)
salarios
aumentos
salarios+aumentos

In [ ]:
aumentos.perc <- c(0.1, 0.2, 0.15, 0.08, 0.09, 0.12)
salarios
salarios*aumentos.perc
salarios + salarios*aumentos.perc

In [ ]:
base <- 20
altura <- 15
area <- base*altura
area

In [ ]:
# Dá para fazer mais contas!
salarios*(1+aumentos.perc)

## Reciclagem
Tente as seguintes contas:
* `v1+v2` com `v1 <- c(1,2,3,4)` e `v2 <- c(10,20)`
* `v1+v3` com `v1` como anteriormente e `v3 <- c(10,20,30)`

In [ ]:
v1 <- c(1,2,3,4)
v2 <- c(10,20)
v1+v2

In [ ]:
sazonalidade <- c(1000, 200, -300, 500)
sorvete <- c(2000, 2100, 1950, 2000, 1900, 2100, 2050, 2000)
sorvete + sazonalidade

In [ ]:
anos <- c(2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023,
          2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024)
meses <- c("jan", "fev", "mar", "abr", "mai", "jun", "jul", "ago", "set", "out", "nov", "dez")
paste(meses,anos,sep="/")

In [ ]:
v1
v3 <- c(10,20,30)
v1+v3 # c(1,2,3,4) + c(10,20,30,10)

# Vetores e operadores lógicos
Operadores lógicos
* `&`: E
* `|`: OU
* `!`: NÃO
* `==`, `!=`: igual, diferente
* `>`, `<`, `>=`, `<=`
* `%in%`: pertencer

In [ ]:
!TRUE

In [ ]:
1 %in% c(1,2,3)

In [ ]:
p <- c(TRUE, FALSE)
q <- c(TRUE, TRUE, FALSE, FALSE)

p
q

In [ ]:
!p

In [ ]:
c(p,p)
q
p & q

In [ ]:
c(p,p)
q
p | q

In [ ]:
tabela <- data.frame(p,q,p&q,p|q)
names(tabela) <- c("p", "q", "p E q", "p OU q")
tabela

In [ ]:
2+2 == 5

In [ ]:
dias.mes <- c(31,29,31,30,31,30,31,31,30,31,30,31)
names(dias.mes) <- c("Jan","Fev","Mar","Abr","Mai","Jun","Jul","Ago","Set","Out","Nov","Dez")
dias.mes

In [ ]:
29 <= 30
31 <= 30

In [ ]:
c(29, 31) <= 30

In [ ]:
dias.mes

In [ ]:
# O que isso faz?
dias.mes <= 30

In [ ]:
# E isso?
dias.mes[dias.mes <= 30]

In [ ]:
v <- 11:15
quero <- c(TRUE, TRUE, FALSE, TRUE, FALSE)
v
quero
v[quero]

In [ ]:
quero[quero]

In [ ]:
dias.mes[dias.mes <= 30]

In [ ]:
TRUE + TRUE + FALSE + FALSE + TRUE # Quantidade de verdadeiros

In [ ]:
sum(dias.mes <= 30)

In [ ]:
# Outro exemplo: simulando notas do ENEM
# Não se preocupe com a linha a seguir
notas <- trunc(rnorm(10000, mean=500, sd=100))
# Caso você esteja curioso: rnorm sorteia 10000 notas com
# média 500 e desvio padrão 100, usando a distribuição normal
# trunc aproxima para o inteiro mais próximo
notas

In [ ]:
# Quantas são as notas maiores do que 600?
notas[notas > 600]   # Quais são as notas?
sum(notas > 600)

In [ ]:
notas_ord <- sort(notas)
notas_ord[notas_ord > 600]

In [ ]:
mean(notas > 600)

In [ ]:
sum(notas >= 400 & notas <= 600)

In [ ]:
sum(400 <= notas <= 600)

# Exercícios
1. Use um objeto para guardar os números de $0$ a $5$ (inclusive).

> a) Escreva um código que retorne o primeiro elemento.

> b) Multiplique tudo por $-1$ e guarde em outro vetor.

In [ ]:
# Exercício 1
numeros <- 0:5
# Item a
numeros[1]
# Item b
outro <- numeros*(-1)
outro <- -numeros    # mesmo resultado
outro

[1] 0

[1]  0 -1 -2 -3 -4 -5

2. Crie um vetor `frutas` com o nome de três frutas.

> a) Faça e investigue: `length(frutas)`

> b) Faça e investigue: `paste("eu gosto de", frutas)`

In [ ]:
# Exercício 2
frutas <- c("banana", "maçã", "uva", "murango")
paste("eu gosto de", frutas)

[1] "eu gosto de banana"  "eu gosto de maçã"    "eu gosto de uva"
[4] "eu gosto de murango"

In [ ]:
paste("Hmmmmm... bolo de", frutas)

[1] "Hmmmmm... bolo de banana"  "Hmmmmm... bolo de maçã"
[3] "Hmmmmm... bolo de uva"     "Hmmmmm... bolo de murango"

In [ ]:
nchar(frutas)

[1] 6 4 3 7

3. Calcule a soma dos números de $1$ a $100$ usando `sum`.

In [ ]:
# Exercício 3
sum(1:100)

[1] 5050

4. Crie um objeto `n <- 100`. Calcule a soma dos números de $1$ a $n$. Qual é a vantagem desse código com relação ao problema anterior?

In [ ]:
# Exercício 4
n <- 100

sum(1:n)

[1] 5050

In [ ]:
n <- readline("Digite n: ")
n <- as.integer(n)
paste("A soma de 1 a", n, "é", sum(1:n))

Digite n: 100

[1] "A soma de 1 a 100 é 5050"

5. Seja
```
 dolar_subiu <- c(TRUE, TRUE, FALSE, TRUE, TRUE, FALSE).
```
Faça e investigue:

> a) `dolar_subiu[2]`

> b) `sum(dolar_subiu)`

> c) `mean(dolar_subiu)`

In [ ]:
# Exercício 5
dolar_subiu <- c(TRUE, TRUE, FALSE, TRUE, TRUE, FALSE)
dolar_subiu[2]
sum(dolar_subiu)    # Quantidade de dias em que o dólar subiu
mean(dolar_subiu)   # mean = média    proporção de dias em que o dólar subiu

[1] TRUE

[1] 4

[1] 0.6666667

6. Suponha que você trabalha em uma empresa e, a partir de uma pesquisa de mercado, tem um vetor `gosto` com `TRUE` se a pessoa gostou de um produto e `FALSE` se não gostou. Como você calcularia a porcentagem de pessoas que gostaram do produto?

In [ ]:
# Exercício 6
# Exemplo de gosto:
gosto <- c(TRUE, FALSE, FALSE, TRUE, FALSE)
mean(gosto)

[1] 0.4

7. Execute o código a seguir, que sorteia um número entre 0 e 10 e guarda no objeto `segredo`.
```
 segredo <- sample(0:10,1)
```
Sem olhar a variável `segredo` (_sem spoiler!_), escreva um código que

> a) testa se `segredo` é maior ou igual a $0$

> b) testa se `segredo` é maior do que $5$

> c) testa se `segredo` é par

In [ ]:
# Exercício 7
segredo <- sample(0:10,1)

In [ ]:
segredo >= 0

[1] TRUE

In [ ]:
segredo > 5

[1] TRUE

In [ ]:
segredo %% 2 == 0

[1] TRUE

In [ ]:
segredo == 6

[1] TRUE

In [ ]:
# Mega Sena
sample(1:60, 6)

[1] 16 21 42 55 59 48

In [ ]:
sabores <- c("Muçarela", "Calabresa", "Portuguesa", "Baiana", "Bauru", "Quatro Queijos")

In [ ]:
table(sample(sabores, 1000, replace=TRUE, prob=c(0.30, 0.25, 0.15, 0.10, 0.10, 0.10)))

        Baiana          Bauru      Calabresa       Muçarela     Portuguesa
            92            113            267            297            146
Quatro Queijos
            85

8. Escreva um código em R que retorne os valores maiores do que $100$ do vetor
```
    teste <- c(201,20,30,202,40,50:150).
```

In [ ]:
# Exercício 8
teste <- c(201,20,30,202,40,50:150)
teste

9. Defina `numeros <- -4:4`.

> a) Escreva um código que devolva os valores positivos de `numeros`.

> b) Escreva um código que devolva os valores negativos de `numeros`.

> c) Escreva um código que devolva os valores de `numeros` cujos quadrados são menores do que $4$.

In [ ]:
# Exercício 9
numeros <- -4:4

# item c
numeros[numeros^2 < 4]

[1] -1  0  1

# Data frames
## Como criar data frames
Veja https://datatofish.com/create-dataframe-in-r/
## Usando um exemplo de data frame
O R tem vários conjuntos de dados prontos. Um deles é o `mtcars`, outro é o `iris`.

In [ ]:
mtcars

                    mpg  cyl disp  hp  drat wt    qsec  vs am gear carb
Mazda RX4           21.0 6   160.0 110 3.90 2.620 16.46 0  1  4    4
Mazda RX4 Wag       21.0 6   160.0 110 3.90 2.875 17.02 0  1  4    4
Datsun 710          22.8 4   108.0  93 3.85 2.320 18.61 1  1  4    1
Hornet 4 Drive      21.4 6   258.0 110 3.08 3.215 19.44 1  0  3    1
Hornet Sportabout   18.7 8   360.0 175 3.15 3.440 17.02 0  0  3    2
Valiant             18.1 6   225.0 105 2.76 3.460 20.22 1  0  3    1
Duster 360          14.3 8   360.0 245 3.21 3.570 15.84 0  0  3    4
Merc 240D           24.4 4   146.7  62 3.69 3.190 20.00 1  0  4    2
Merc 230            22.8 4   140.8  95 3.92 3.150 22.90 1  0  4    2
Merc 280            19.2 6   167.6 123 3.92 3.440 18.30 1  0  4    4
Merc 280C           17.8 6   167.6 123 3.92 3.440 18.90 1  0  4    4
Merc 450SE          16.4 8   275.8 180 3.07 4.070 17.40 0  0  3    3
Merc 450SL          17.3 8   275.8 180 3.07 3.730 17.60 0  0  3    3
Merc 450SLC         15.2 8   275.8 180 3.07 3.780 18.00 0  0  3    3
Cadillac Fleetwood  10.4 8   472.0 205 2.93 5.250 17.98 0  0  3    4
Lincoln Continental 10.4 8   460.0 215 3.00 5.424 17.82 0  0  3    4
Chrysler Imperial   14.7 8   440.0 230 3.23 5.345 17.42 0  0  3    4
Fiat 128            32.4 4    78.7  66 4.08 2.200 19.47 1  1  4    1
Honda Civic         30.4 4    75.7  52 4.93 1.615 18.52 1  1  4    2
Toyota Corolla      33.9 4    71.1  65 4.22 1.835 19.90 1  1  4    1
Toyota Corona       21.5 4   120.1  97 3.70 2.465 20.01 1  0  3    1
Dodge Challenger    15.5 8   318.0 150 2.76 3.520 16.87 0  0  3    2
AMC Javelin         15.2 8   304.0 150 3.15 3.435 17.30 0  0  3    2
Camaro Z28          13.3 8   350.0 245 3.73 3.840 15.41 0  0  3    4
Pontiac Firebird    19.2 8   400.0 175 3.08 3.845 17.05 0  0  3    2
Fiat X1-9           27.3 4    79.0  66 4.08 1.935 18.90 1  1  4    1
Porsche 914-2       26.0 4   120.3  91 4.43 2.140 16.70 0  1  5    2
Lotus Europa        30.4 4    95.1 113 3.77 1.513 16.90 1  1  5    2
Ford Pantera L      15.8 8   351.0 264 4.22 3.170 14.50 0  1  5    4
Ferrari Dino        19.7 6   145.0 175 3.62 2.770 15.50 0  1  5    6
Maserati Bora       15.0 8   301.0 335 3.54 3.570 14.60 0  1  5    8
Volvo 142E          21.4 4   121.0 109 4.11 2.780 18.60 1  1  4    2

In [ ]:
help(mtcars)

In [ ]:
?mtcars

In [ ]:
class(mtcars)

[1] "data.frame"

In [ ]:
rownames(mtcars)

 [1] "Mazda RX4"           "Mazda RX4 Wag"       "Datsun 710"
 [4] "Hornet 4 Drive"      "Hornet Sportabout"   "Valiant"
 [7] "Duster 360"          "Merc 240D"           "Merc 230"
[10] "Merc 280"            "Merc 280C"           "Merc 450SE"
[13] "Merc 450SL"          "Merc 450SLC"         "Cadillac Fleetwood"
[16] "Lincoln Continental" "Chrysler Imperial"   "Fiat 128"
[19] "Honda Civic"         "Toyota Corolla"      "Toyota Corona"
[22] "Dodge Challenger"    "AMC Javelin"         "Camaro Z28"
[25] "Pontiac Firebird"    "Fiat X1-9"           "Porsche 914-2"
[28] "Lotus Europa"        "Ford Pantera L"      "Ferrari Dino"
[31] "Maserati Bora"       "Volvo 142E"

In [ ]:
colnames(mtcars)

 [1] "mpg"  "cyl"  "disp" "hp"   "drat" "wt"   "qsec" "vs"   "am"   "gear"
[11] "carb"

In [ ]:
names(mtcars)

 [1] "mpg"  "cyl"  "disp" "hp"   "drat" "wt"   "qsec" "vs"   "am"   "gear"
[11] "carb"

In [ ]:
mtcars[3,4]

[1] 93

In [ ]:
mtcars

                    mpg  cyl disp  hp  drat wt    qsec  vs am gear carb
Mazda RX4           21.0 6   160.0 110 3.90 2.620 16.46 0  1  4    4
Mazda RX4 Wag       21.0 6   160.0 110 3.90 2.875 17.02 0  1  4    4
Datsun 710          22.8 4   108.0  93 3.85 2.320 18.61 1  1  4    1
Hornet 4 Drive      21.4 6   258.0 110 3.08 3.215 19.44 1  0  3    1
Hornet Sportabout   18.7 8   360.0 175 3.15 3.440 17.02 0  0  3    2
Valiant             18.1 6   225.0 105 2.76 3.460 20.22 1  0  3    1
Duster 360          14.3 8   360.0 245 3.21 3.570 15.84 0  0  3    4
Merc 240D           24.4 4   146.7  62 3.69 3.190 20.00 1  0  4    2
Merc 230            22.8 4   140.8  95 3.92 3.150 22.90 1  0  4    2
Merc 280            19.2 6   167.6 123 3.92 3.440 18.30 1  0  4    4
Merc 280C           17.8 6   167.6 123 3.92 3.440 18.90 1  0  4    4
Merc 450SE          16.4 8   275.8 180 3.07 4.070 17.40 0  0  3    3
Merc 450SL          17.3 8   275.8 180 3.07 3.730 17.60 0  0  3    3
Merc 450SLC         15.2 8   275.8 180 3.07 3.780 18.00 0  0  3    3
Cadillac Fleetwood  10.4 8   472.0 205 2.93 5.250 17.98 0  0  3    4
Lincoln Continental 10.4 8   460.0 215 3.00 5.424 17.82 0  0  3    4
Chrysler Imperial   14.7 8   440.0 230 3.23 5.345 17.42 0  0  3    4
Fiat 128            32.4 4    78.7  66 4.08 2.200 19.47 1  1  4    1
Honda Civic         30.4 4    75.7  52 4.93 1.615 18.52 1  1  4    2
Toyota Corolla      33.9 4    71.1  65 4.22 1.835 19.90 1  1  4    1
Toyota Corona       21.5 4   120.1  97 3.70 2.465 20.01 1  0  3    1
Dodge Challenger    15.5 8   318.0 150 2.76 3.520 16.87 0  0  3    2
AMC Javelin         15.2 8   304.0 150 3.15 3.435 17.30 0  0  3    2
Camaro Z28          13.3 8   350.0 245 3.73 3.840 15.41 0  0  3    4
Pontiac Firebird    19.2 8   400.0 175 3.08 3.845 17.05 0  0  3    2
Fiat X1-9           27.3 4    79.0  66 4.08 1.935 18.90 1  1  4    1
Porsche 914-2       26.0 4   120.3  91 4.43 2.140 16.70 0  1  5    2
Lotus Europa        30.4 4    95.1 113 3.77 1.513 16.90 1  1  5    2
Ford Pantera L      15.8 8   351.0 264 4.22 3.170 14.50 0  1  5    4
Ferrari Dino        19.7 6   145.0 175 3.62 2.770 15.50 0  1  5    6
Maserati Bora       15.0 8   301.0 335 3.54 3.570 14.60 0  1  5    8
Volvo 142E          21.4 4   121.0 109 4.11 2.780 18.60 1  1  4    2

In [ ]:
mtcars[3, ]

           mpg  cyl disp hp drat wt   qsec  vs am gear carb
Datsun 710 22.8 4   108  93 3.85 2.32 18.61 1  1  4    1

In [ ]:
mtcars[1:3, ]

              mpg  cyl disp hp  drat wt    qsec  vs am gear carb
Mazda RX4     21.0 6   160  110 3.90 2.620 16.46 0  1  4    4
Mazda RX4 Wag 21.0 6   160  110 3.90 2.875 17.02 0  1  4    4
Datsun 710    22.8 4   108   93 3.85 2.320 18.61 1  1  4    1

In [ ]:
mtcars[1:3, c("cyl", "hp")]

              cyl hp
Mazda RX4     6   110
Mazda RX4 Wag 6   110
Datsun 710    4    93

In [ ]:
mtcars$cyl

 [1] 6 6 4 6 8 6 8 4 4 6 6 8 8 8 8 8 8 4 4 4 4 8 8 8 8 4 4 4 8 6 8 4

In [ ]:
mtcars["cyl"]

                    cyl
Mazda RX4           6
Mazda RX4 Wag       6
Datsun 710          4
Hornet 4 Drive      6
Hornet Sportabout   8
Valiant             6
Duster 360          8
Merc 240D           4
Merc 230            4
Merc 280            6
Merc 280C           6
Merc 450SE          8
Merc 450SL          8
Merc 450SLC         8
Cadillac Fleetwood  8
Lincoln Continental 8
Chrysler Imperial   8
Fiat 128            4
Honda Civic         4
Toyota Corolla      4
Toyota Corona       4
Dodge Challenger    8
AMC Javelin         8
Camaro Z28          8
Pontiac Firebird    8
Fiat X1-9           4
Porsche 914-2       4
Lotus Europa        4
Ford Pantera L      8
Ferrari Dino        6
Maserati Bora       8
Volvo 142E          4

In [ ]:
mtcars[mtcars$cyl > 6,]

                    mpg  cyl disp  hp  drat wt    qsec  vs am gear carb
Hornet Sportabout   18.7 8   360.0 175 3.15 3.440 17.02 0  0  3    2
Duster 360          14.3 8   360.0 245 3.21 3.570 15.84 0  0  3    4
Merc 450SE          16.4 8   275.8 180 3.07 4.070 17.40 0  0  3    3
Merc 450SL          17.3 8   275.8 180 3.07 3.730 17.60 0  0  3    3
Merc 450SLC         15.2 8   275.8 180 3.07 3.780 18.00 0  0  3    3
Cadillac Fleetwood  10.4 8   472.0 205 2.93 5.250 17.98 0  0  3    4
Lincoln Continental 10.4 8   460.0 215 3.00 5.424 17.82 0  0  3    4
Chrysler Imperial   14.7 8   440.0 230 3.23 5.345 17.42 0  0  3    4
Dodge Challenger    15.5 8   318.0 150 2.76 3.520 16.87 0  0  3    2
AMC Javelin         15.2 8   304.0 150 3.15 3.435 17.30 0  0  3    2
Camaro Z28          13.3 8   350.0 245 3.73 3.840 15.41 0  0  3    4
Pontiac Firebird    19.2 8   400.0 175 3.08 3.845 17.05 0  0  3    2
Ford Pantera L      15.8 8   351.0 264 4.22 3.170 14.50 0  1  5    4
Maserati Bora       15.0 8   301.0 335 3.54 3.570 14.60 0  1  5    8

## Acessando colunas diretamente pelo nome
Usamos `$`. Por exemplo, para acessar a coluna `mpg` de `mtcars` usamos `mtcars$mpg`.

In [ ]:
mtcars

In [ ]:
mtcars$mpg

In [ ]:
mtcars['mpg']

## Coordenadas em data frames
Sendo `df` um data frame, `df[linha, coluna]` nos dá o elemento da linha `linha` e coluna `coluna`. Lembre que no R começamos a contar de 1.

In [ ]:
mtcars

In [ ]:
mtcars[1,2] # Note que os nomes das linhas não contam como coluna

In [ ]:
mtcars["Fiat 128", "mpg"]

In [ ]:
# Se não colocar vírgula no meio, o R entende coluna
mtcars[1]    # Primeira coluna

In [ ]:
# Qual é a diferença?
mtcars[1,2]

In [ ]:
# Qual é a diferença?
mtcars[c(1,2)]

In [ ]:
mtcars[c(1,2),1:3]

In [ ]:
# Voltando a usar vírgula
mtcars[1,]

In [ ]:
mtcars[,1]

In [ ]:
mtcars[1]

## Juntando tudo: filtros e data frames
Podemos usar filtros lógicos para escolher elementos que satisfazem critérios em data frames

In [ ]:
mtcars$cyl

In [ ]:
mtcars$cyl == 4

In [ ]:
mtcars[mtcars$cyl == 4,] # Não se esqueça da vírgula!

In [ ]:
# Filtre os carros com mpg > 20!
mtcars[mtcars$mpg > 20,]

In [ ]:
# Dá para fazer os dois filtros ao mesmo tempo?
mtcars[mtcars$cyl==4 & mtcars$mpg>20,]

In [ ]:
# Dá para ranquear os carros de acordo com o consumo?
mtcars[order(mtcars$mpg, decreasing=TRUE),]

# Exercícios: data frames
1. Experimente os seguintes comandos e veja quais dão um vetor com a coluna `mpg` do `mtcars`.

> a) `mtcars$mpg`

> b) `mtcars[ , 3]`

> c) `mtcars("mpg")`

> d) `mtcars[ , "mpg"]`

> e) `mtcars.mpg`

> f) `mtcars[ , 1]`

> g) `mtcars[1, 1]`

> h) `mpg$mtcars`

2. Use a função `str()`. O que ela faz? Lembre que você pode fazer `?str`.

3. E a função `names`, para que serve?

4. Mais um data frame que vem com o R: `airquality`.

> a) Quantas linhas e colunas tem?

> b) Use a função `head()` nele. O que essa função faz?

> c) Encontre os nomes das colunas.

> d) Qual é a classe da coluna `Ozone`?

5. Ainda sobre o data frame airquality:

> a) Quantos `NA`s tem a coluna `Solar.R`?

> b) Exiba as linhas em que `Solar.R` é `NA`.

> c) Exiba as linhas em que `Solar.R` não é `NA`.

In [ ]:
?airquality