# Data frames
## Como criar data frames
Veja https://datatofish.com/create-dataframe-in-r/
## Usando um exemplo de data frame
O R tem vários conjuntos de dados prontos. Um deles é o `mtcars`, outro é o `iris`.

In [ ]:
mtcars

                    mpg  cyl disp  hp  drat wt    qsec  vs am gear carb
Mazda RX4           21.0 6   160.0 110 3.90 2.620 16.46 0  1  4    4
Mazda RX4 Wag       21.0 6   160.0 110 3.90 2.875 17.02 0  1  4    4
Datsun 710          22.8 4   108.0  93 3.85 2.320 18.61 1  1  4    1
Hornet 4 Drive      21.4 6   258.0 110 3.08 3.215 19.44 1  0  3    1
Hornet Sportabout   18.7 8   360.0 175 3.15 3.440 17.02 0  0  3    2
Valiant             18.1 6   225.0 105 2.76 3.460 20.22 1  0  3    1
Duster 360          14.3 8   360.0 245 3.21 3.570 15.84 0  0  3    4
Merc 240D           24.4 4   146.7  62 3.69 3.190 20.00 1  0  4    2
Merc 230            22.8 4   140.8  95 3.92 3.150 22.90 1  0  4    2
Merc 280            19.2 6   167.6 123 3.92 3.440 18.30 1  0  4    4
Merc 280C           17.8 6   167.6 123 3.92 3.440 18.90 1  0  4    4
Merc 450SE          16.4 8   275.8 180 3.07 4.070 17.40 0  0  3    3
Merc 450SL          17.3 8   275.8 180 3.07 3.730 17.60 0  0  3    3
Merc 450SLC         15.2 8   275.8 180 3.07 3.780 18.00 0  0  3    3
Cadillac Fleetwood  10.4 8   472.0 205 2.93 5.250 17.98 0  0  3    4
Lincoln Continental 10.4 8   460.0 215 3.00 5.424 17.82 0  0  3    4
Chrysler Imperial   14.7 8   440.0 230 3.23 5.345 17.42 0  0  3    4
Fiat 128            32.4 4    78.7  66 4.08 2.200 19.47 1  1  4    1
Honda Civic         30.4 4    75.7  52 4.93 1.615 18.52 1  1  4    2
Toyota Corolla      33.9 4    71.1  65 4.22 1.835 19.90 1  1  4    1
Toyota Corona       21.5 4   120.1  97 3.70 2.465 20.01 1  0  3    1
Dodge Challenger    15.5 8   318.0 150 2.76 3.520 16.87 0  0  3    2
AMC Javelin         15.2 8   304.0 150 3.15 3.435 17.30 0  0  3    2
Camaro Z28          13.3 8   350.0 245 3.73 3.840 15.41 0  0  3    4
Pontiac Firebird    19.2 8   400.0 175 3.08 3.845 17.05 0  0  3    2
Fiat X1-9           27.3 4    79.0  66 4.08 1.935 18.90 1  1  4    1
Porsche 914-2       26.0 4   120.3  91 4.43 2.140 16.70 0  1  5    2
Lotus Europa        30.4 4    95.1 113 3.77 1.513 16.90 1  1  5    2
Ford Pantera L      15.8 8   351.0 264 4.22 3.170 14.50 0  1  5    4
Ferrari Dino        19.7 6   145.0 175 3.62 2.770 15.50 0  1  5    6
Maserati Bora       15.0 8   301.0 335 3.54 3.570 14.60 0  1  5    8
Volvo 142E          21.4 4   121.0 109 4.11 2.780 18.60 1  1  4    2

# Exercícios: data frames
1. Experimente os seguintes comandos e veja quais dão um vetor com a coluna `mpg` do `mtcars`.

> a) `mtcars$mpg`

> b) `mtcars[ , 3]`

> c) `mtcars("mpg")`

> d) `mtcars[ , "mpg"]`

> e) `mtcars.mpg`

> f) `mtcars[ , 1]`

> g) `mtcars[1, 1]`

> h) `mpg$mtcars`

In [ ]:
# Exercício 1
mtcars$mpg

In [ ]:
mtcars[ , 1]

In [ ]:
mtcars("mpg")

In [ ]:
mtcars["mpg"]

In [ ]:
mtcars.mpg

In [ ]:
mpg$mtcars

2. Use a função `str()`. O que ela faz? Lembre que você pode fazer `?str`.

In [ ]:
# Exercício 2
str(iris)

3. E a função `names`, para que serve?

In [ ]:
# Exercício 3
names(mtcars)   # nomes das colunas (variáveis)

4. Mais um data frame que vem com o R: `airquality`.

> a) Quantas linhas e colunas tem?

> b) Use a função `head()` nele. O que essa função faz?

> c) Encontre os nomes das colunas.

> d) Qual é a classe da coluna `Ozone`?

In [ ]:
# Exercício 4
dim(airquality)

In [ ]:
airquality

In [ ]:
head(airquality)

In [ ]:
tail(airquality)

In [ ]:
names(airquality)

In [ ]:
class(airquality$Ozone)

5. Ainda sobre o data frame `airquality`:

> a) Quantos `NA`s tem a coluna `Solar.R`?

> b) Exiba as linhas em que `Solar.R` é `NA`.

> c) Exiba as linhas em que `Solar.R` não é `NA`.

In [ ]:
dados.com.NA = c(NA,1,2,4,NA)
dados.com.NA == NA
is.na(dados.com.NA)
sum(is.na(dados.com.NA))

[1] NA NA NA NA NA

[1]  TRUE FALSE FALSE FALSE  TRUE

[1] 2

In [ ]:
airquality$Solar.R

In [ ]:
is.na(airquality$Solar.R)

In [ ]:
# is.na verifica se é NA; depois soma
sum(is.na(airquality$Solar.R))

In [ ]:
# Exercício 5

In [ ]:
airquality[!is.na(airquality$Solar.R),]

## Funções
* Já usamos algumas: `sqrt()`, `class()`, `c()`, `paste()`, `gsub()`...
* Formato: `nome_da_funcao(arg1, arg2, ..., argk)`
* Separamos argumentos por vírgula!
* Algumas usam vetor como argumento

In [ ]:
sum(c(1,2))

In [ ]:
sum(c(1,2),c(3,4))

[1] 10

In [ ]:
mean(c(1,2))

In [ ]:
mean(c(1,2),3)

In [ ]:
# Média do mpg do mtcars?
mean(mtcars$mpg)

In [ ]:
# E se tiver NA?
mean(c(1,3,NA))

In [ ]:
mean(airquality$Ozone)

In [ ]:
# Como lidar com isso? Argumento opcional: na.rm=TRUE
mean(c(1,3,NA), na.rm=TRUE)

In [ ]:
mean(airquality$Ozone, na.rm=TRUE)

In [ ]:
?mean

## A função `seq()`
Para sequências aritméticas

In [ ]:
seq(from=4, to=10, by=2)

In [ ]:
seq(4, 10, 2)

In [ ]:
seq(by=2, to=10, from=4)

In [ ]:
seq(2,10,4)

## Funções para data frames
* `head()`: seis primeiras linhas
* `tail()`: seis últimas linhas (bom para ver se os últimos dados entraram no data frame)
* `dim()`: número de linhas e colunas
* `names()`: nomes das variáveis (colunas)
* `str()`: estrutura do data frame
* `cbind()`: junta tabelas lado a lado (`c` = column)
* `rbind()`: junta tabelas uma sobre a outra (`r` = row)

In [ ]:
str(iris)

In [ ]:
names(iris)

In [ ]:
head(iris)

In [ ]:
tail(iris)

In [ ]:
dim(iris)

In [ ]:
tabela <- mtcars
rbind(tabela,tabela)
tabela2 <- iris
cbind(tabela2,tabela2)

# Criando nossas próprias funções
Podemos criar funções! A sintaxe é
```
nome_da_funcao <- function(arg1, arg2, ..., argk){
   # tarefa a ser realizada
}
```

In [ ]:
# Função que calcula a soma de dois números
minha_soma <- function(x,y){
  soma <- x+y
  soma
}

In [ ]:
class(minha_soma)

In [ ]:
minha_soma(2,3)

In [ ]:
minha_soma(c(1,2),c(3,4))

[1] 4 6

In [ ]:
c(1,2) + c(3,4)

In [ ]:
# Podemos usar return para explicitar o que deve ser retornado
minha_soma2 <- function(x,y){
  return(x+y)
}

In [ ]:
minha_soma2(c(3,4),c(1,5))

In [ ]:
# Posso colocar em um objeto?
resultado <- minha_soma(3,4)

In [ ]:
resultado

## Variáveis locais e globais
O `x` e o `y` dentro de `minha_soma` são _locais_, ou seja, só existem dentro da função. Quando a função terminou de rodar, `x` e `y` somem.

In [ ]:
# Vai dar erro
soma

In [ ]:
porcento <- function(valor, porc){
  return(valor*porc/100)
}

In [ ]:
porcento(11000,20)

## Mais sobre funções
* Curso online: https://livro.curso-r.com/3-11-maisFuncoes.html#exerc%C3%ADcios-7
* Aprofundamento: https://bookdown.org/rdpeng/rprogdatascience/functions.html#functions-in-r

(No aprofundamento tem loops, que vamos aprender mais tarde)

## Exercícios sobre funções
1. Crie uma função que receba um número e retorne o quadrado deste número.

In [ ]:
# Exercício 1
quadrado <- function(x){
  return(x*x)
}

In [ ]:
quadrado(8)

2. Crie uma função que receba 2 números e devolva a raiz quadrada da soma desses números.

In [ ]:
# Exercício 2
receba <- function(x,y){
  return(sqrt(x+y))
}

In [ ]:
receba(1,7)

3. Rode `help(sample)` para descobrir o que a função `sample()` faz. Em seguida

> a) use-a para escrever uma função que devolva uma linha aleatória de um dataframe;

> b) generalize a função para retornar um número qualquer de linhas, que poderá ser escolhido por quem for usá-la.

In [ ]:
# Exercício 3
?sample

In [ ]:
sample(60, 6)

In [ ]:
sample(6, 100, replace=TRUE)

In [ ]:
mtcars

                    mpg  cyl disp  hp  drat wt    qsec  vs am gear carb
Mazda RX4           21.0 6   160.0 110 3.90 2.620 16.46 0  1  4    4
Mazda RX4 Wag       21.0 6   160.0 110 3.90 2.875 17.02 0  1  4    4
Datsun 710          22.8 4   108.0  93 3.85 2.320 18.61 1  1  4    1
Hornet 4 Drive      21.4 6   258.0 110 3.08 3.215 19.44 1  0  3    1
Hornet Sportabout   18.7 8   360.0 175 3.15 3.440 17.02 0  0  3    2
Valiant             18.1 6   225.0 105 2.76 3.460 20.22 1  0  3    1
Duster 360          14.3 8   360.0 245 3.21 3.570 15.84 0  0  3    4
Merc 240D           24.4 4   146.7  62 3.69 3.190 20.00 1  0  4    2
Merc 230            22.8 4   140.8  95 3.92 3.150 22.90 1  0  4    2
Merc 280            19.2 6   167.6 123 3.92 3.440 18.30 1  0  4    4
Merc 280C           17.8 6   167.6 123 3.92 3.440 18.90 1  0  4    4
Merc 450SE          16.4 8   275.8 180 3.07 4.070 17.40 0  0  3    3
Merc 450SL          17.3 8   275.8 180 3.07 3.730 17.60 0  0  3    3
Merc 450SLC         15.2 8   275.8 180 3.07 3.780 18.00 0  0  3    3
Cadillac Fleetwood  10.4 8   472.0 205 2.93 5.250 17.98 0  0  3    4
Lincoln Continental 10.4 8   460.0 215 3.00 5.424 17.82 0  0  3    4
Chrysler Imperial   14.7 8   440.0 230 3.23 5.345 17.42 0  0  3    4
Fiat 128            32.4 4    78.7  66 4.08 2.200 19.47 1  1  4    1
Honda Civic         30.4 4    75.7  52 4.93 1.615 18.52 1  1  4    2
Toyota Corolla      33.9 4    71.1  65 4.22 1.835 19.90 1  1  4    1
Toyota Corona       21.5 4   120.1  97 3.70 2.465 20.01 1  0  3    1
Dodge Challenger    15.5 8   318.0 150 2.76 3.520 16.87 0  0  3    2
AMC Javelin         15.2 8   304.0 150 3.15 3.435 17.30 0  0  3    2
Camaro Z28          13.3 8   350.0 245 3.73 3.840 15.41 0  0  3    4
Pontiac Firebird    19.2 8   400.0 175 3.08 3.845 17.05 0  0  3    2
Fiat X1-9           27.3 4    79.0  66 4.08 1.935 18.90 1  1  4    1
Porsche 914-2       26.0 4   120.3  91 4.43 2.140 16.70 0  1  5    2
Lotus Europa        30.4 4    95.1 113 3.77 1.513 16.90 1  1  5    2
Ford Pantera L      15.8 8   351.0 264 4.22 3.170 14.50 0  1  5    4
Ferrari Dino        19.7 6   145.0 175 3.62 2.770 15.50 0  1  5    6
Maserati Bora       15.0 8   301.0 335 3.54 3.570 14.60 0  1  5    8
Volvo 142E          21.4 4   121.0 109 4.11 2.780 18.60 1  1  4    2

In [ ]:
nrow(mtcars)

In [ ]:
ncol(mtcars)

In [ ]:
sample(nrow(mtcars),1)

In [ ]:
mtcars[8,]

In [ ]:
mtcars[sample(nrow(mtcars),1),]

In [ ]:
sorteia <- function(df){
  return(df[sample(nrow(df),1),])
}

In [ ]:
sorteia(iris)

# Controle de fluxo (loops, se-então-senão)
O R também aceita loops (`if`, `else`, `for`, `while`)

Veja mais em:
* https://livro.curso-r.com/3-12-controle-de-fluxo.html#controle-de-fluxo
* https://bookdown.org/rdpeng/rprogdatascience/control-structures.html

Os loops listados acima costumam ser lentos. Em geral usamos as funções `*apply`. Veja mais em https://bookdown.org/rdpeng/rprogdatascience/loop-functions.html

## `if` e `else`
Sintaxe:
```
if(condição){
  # faça coisas
}
else{
  # faça outras coisas
}
```

In [ ]:
x <- 2

if(x == 1){
  Sys.time()   # Coloca hora e data na tela
}

In [ ]:
x <- 1

if(x == 1){
  Sys.time()   # Coloca hora e data na tela
}

Podemos adaptar a função `minha_soma()` para tratar erros.

In [ ]:
minha_soma <- function(x, y) {
  if (class(x) == "numeric" & class(y) == "numeric") {
     x + y
  }
}

In [ ]:
minha_soma(3,2)

In [ ]:
minha_soma("a",2)

## Exercícios
1. Faça uma função que multiplique dois números e coloque na tela uma mensagem de erro personalizada quando algum dos dois números não é da classe `numeric`.

In [ ]:
# Solução

In [ ]:
# Testes

2. Crie um script que pega um `nome` como argumento e retorna `Olá nome!`.

In [ ]:
# Solução

In [ ]:
# Testes

3. Crie uma função que recebe três inteiros e retorna sua soma. Porém, quando algum valor é divisível por 3 o mesmo não é considerado na soma. Casos todos os três sejam divisíveis por 3 a soma deve resultar em 0.

In [ ]:
# Solução

In [ ]:
# Testes

## Usando `else`

In [ ]:
x <- c(1, 3, 10, 15)

if (class(x) == "numeric") {
  sum(x)
} else {
  NA
}

In [ ]:
x <- c(1, 3, 10, "15")

if (class(x) == "numeric") {
  sum(x)
} else {
  NA
}

In [ ]:
x <- 0

if(x < 0) {
  "negativo"
} else if(x == 0) {
  "neutro"
} else if(x > 0) {
  "positivo"
}

## `return()` e `stop()`
* `return()` sai da função imediatamente com a resposta (dentro do `return`).
* `stop()` sai da função imediatamente e coloca mensagem de erro (dentro do `stop`).

In [ ]:
minha_soma_NA <- function(x, y) {
  if (class(x) == "numeric" & class(y) == "numeric") {
     soma <- x + y
     return(soma)
  }
  NA
}

In [ ]:
minha_soma_NA(1, 2)

In [ ]:
minha_soma_NA("a", "b")

In [ ]:
minha_soma_NA(1, "b")

In [ ]:
minha_soma_erro <- function(x, y) {
  if (class(x) != "numeric" | class(y) != "numeric") {
    stop("A classe dos objetos x e y deve ser numérica.")
  }
  x + y
}

In [ ]:
minha_soma_erro(1, 2)

In [ ]:
minha_soma_erro("a", "b")

In [ ]:
minha_soma_erro(1, "b")

## `for`
Sintaxe:
```
for(indice in vetor){
  # Faça coisas
}
```

In [ ]:
numero_de_colunas <- ncol(mtcars)

for (coluna in 1:numero_de_colunas) {
  media <- mean(mtcars[,coluna])

  print(media)
}

In [ ]:
numero_de_colunas <- ncol(mtcars)

# Antes, criamos um vetor vazio.
medias <- c()

for (coluna in 1:numero_de_colunas) {
  medias[coluna] <- mean(mtcars[,coluna])
}

medias

In [ ]:
# A função colMeans() faz isso sem loops!
colMeans(mtcars)

## `while`
Sintaxe:
```
while(condição){
  # Faça coisas
}
```

In [ ]:
i <- 1

while (i < 3){
  print(i)
  i <-  i + 1
}