# Exercícios - vetores
1. Use um objeto para guardar os números de $0$ a $5$ (inclusive).

> a) Escreva um código que retorne o primeiro elemento.

> b) Multiplique tudo por $-1$ e guarde em outro vetor.

In [ ]:
# Exercício 1
goias <- 0:5

In [ ]:
# item a
goias
goias[1]

[1] 0 1 2 3 4 5

[1] 0

In [ ]:
# item b
menos_goias <- goias*(-1)
menos_goias

[1]  0 -1 -2 -3 -4 -5

In [ ]:
-goias # também funciona

[1]  0 -1 -2 -3 -4 -5

2. Crie um vetor `frutas` com o nome de três frutas.

> a) Faça e investigue: `length(frutas)`

> b) Faça e investigue: `paste("eu gosto de", frutas)`

In [ ]:
# Exercício 2
frutas <- c("uva", "banana", "maçã", "morango")
# item a
length(frutas)
# Para quantidade de caracteres, use nchar
nchar(frutas)

[1] 4

[1] 3 6 4 7

In [ ]:
# item b
paste("eu gosto de", frutas)

[1] "eu gosto de uva"     "eu gosto de banana"  "eu gosto de maçã"
[4] "eu gosto de morango"

In [ ]:
paste("Hmmmm, bolo de", frutas)

[1] "Hmmmm, bolo de uva"     "Hmmmm, bolo de banana"  "Hmmmm, bolo de maçã"
[4] "Hmmmm, bolo de morango"

3. Calcule a soma dos números de $1$ a $100$ usando `sum`.

In [ ]:
# Exercício 3
sum(1:100)

[1] 5050

In [ ]:
sum(1:10000000)

[1] 5e+13

4. Crie um objeto `n <- 100`. Calcule a soma dos números de $1$ a $n$. Qual é a vantagem desse código com relação ao problema anterior?

In [ ]:
# Exercício 4
n <- 100
sum(1:n)

[1] 5050

5. Seja
```
 dolar_subiu <- c(TRUE, TRUE, FALSE, TRUE, TRUE, FALSE).
```
Faça e investigue:

> a) `dolar_subiu[2]`

> b) `sum(dolar_subiu)`

> c) `mean(dolar_subiu)`

In [ ]:
# Exercício 5
dolar_subiu <- c(TRUE, TRUE, FALSE, TRUE, TRUE, FALSE)
# Item a
dolar_subiu[2]
# Item b: quantidade de dias em que o dólar subiu
sum(dolar_subiu)
# Item c: mean = média, proporção de dias em que o dólar subiu
mean(dolar_subiu)

[1] TRUE

[1] 4

[1] 0.6666667

Usando dados reais

In [ ]:
install.packages("rbcb")

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

also installing the dependencies ‘zoo’, ‘xts’

In [ ]:
library(rbcb)

In [ ]:
cotacoes <- get_series(c(USDBRL=1), last=10)

Skipping download - using cached version

In [ ]:
cotacoes

   date       USDBRL
1  2026-03-04 5.2091
2  2026-03-05 5.2447
3  2026-03-06 5.2878
4  2026-03-09 5.2139
5  2026-03-10 5.1622
6  2026-03-11 5.1596
7  2026-03-12 5.2051
8  2026-03-13 5.2541
9  2026-03-16 5.2647
10 2026-03-17 5.2022

In [ ]:
diff(cotacoes$USDBRL) > 0

[1]  TRUE  TRUE FALSE FALSE FALSE  TRUE  TRUE  TRUE FALSE

6. Suponha que você trabalha em uma empresa e, a partir de uma pesquisa de mercado, tem um vetor `gosto` com `TRUE` se a pessoa gostou de um produto e `FALSE` se não gostou. Como você calcularia a porcentagem de pessoas que gostaram do produto?

In [ ]:
# Exercício 6
# Exemplo de gosto:
gosto <- c(TRUE, FALSE, FALSE, TRUE, FALSE)

7. Execute o código a seguir, que sorteia um número entre 0 e 10 e guarda no objeto `segredo`.
```
 segredo <- sample(0:10,1)
```
Sem olhar a variável `segredo` (_sem spoiler!_), escreva um código que

> a) testa se `segredo` é maior ou igual a $0$

> b) testa se `segredo` é maior do que $5$

> c) testa se `segredo` é par

In [ ]:
# Exercício 7 - não adicione código aqui (vai sortear de novo)
segredo <- sample(0:10,1)

In [ ]:
sample(1:60, 6)

[1] 23 16  2  8 53 38

In [ ]:
# Adicione código aqui
# item a
segredo > 0

[1] TRUE

In [ ]:
# Item b
segredo > 5

[1] TRUE

In [ ]:
# Item c
segredo %% 2 == 0

[1] TRUE

In [ ]:
segredo == 10

[1] TRUE

In [ ]:
segredo

[1] 10

8. Escreva um código em R que retorne os valores maiores do que $100$ do vetor
```
    teste <- c(201,20,30,202,40,50:150).
```

In [ ]:
# Exercício 8
teste <- c(201,20,30,202,40,50:150)
teste

  [1] 201  20  30 202  40  50  51  52  53  54  55  56  57  58  59  60  61  62
 [19]  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80
 [37]  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98
 [55]  99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116
 [73] 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134
 [91] 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150

In [ ]:
# Resolva o exercício 8 aqui
teste > 100

  [1]  TRUE FALSE FALSE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [13] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [25] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [37] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [49] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE  TRUE  TRUE  TRUE
 [61]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
 [73]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
 [85]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
 [97]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE

In [ ]:
# vetor[critério] nos dá quais elementos do vetor satisfazem o critério
teste[teste > 100]

 [1] 201 202 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
[20] 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136
[39] 137 138 139 140 141 142 143 144 145 146 147 148 149 150

In [ ]:
idades <- c(20, 11, 18, 17, 15, 78, 49, 32)

In [ ]:
# voto obrigatório
idades >= 18 & idades <= 70
idades[idades >= 18 & idades <= 70]

[1]  TRUE FALSE  TRUE FALSE FALSE FALSE  TRUE  TRUE

[1] 20 18 49 32

In [ ]:
# voto opcional
idades > 70 | idades == 16 | idades == 17
idades > 70 | idades %in% c(16, 17)

[1] FALSE FALSE FALSE  TRUE FALSE  TRUE FALSE FALSE

[1] FALSE FALSE FALSE  TRUE FALSE  TRUE FALSE FALSE

9. Defina `numeros <- -4:4`.

> a) Escreva um código que devolva os valores positivos de `numeros`.

> b) Escreva um código que devolva os valores negativos de `numeros`.

> c) Escreva um código que devolva os valores de `numeros` cujos quadrados são menores do que $4$.

In [ ]:
# Exercício 9
numeros <- -4:4
numeros

# Data frames
## Como criar data frames
Veja https://datatofish.com/create-dataframe-in-r/
## Usando um exemplo de data frame
O R tem vários conjuntos de dados prontos. Um deles é o `mtcars`, outro é o `iris`.

In [ ]:
mtcars

                    mpg  cyl disp  hp  drat wt    qsec  vs am gear carb
Mazda RX4           21.0 6   160.0 110 3.90 2.620 16.46 0  1  4    4
Mazda RX4 Wag       21.0 6   160.0 110 3.90 2.875 17.02 0  1  4    4
Datsun 710          22.8 4   108.0  93 3.85 2.320 18.61 1  1  4    1
Hornet 4 Drive      21.4 6   258.0 110 3.08 3.215 19.44 1  0  3    1
Hornet Sportabout   18.7 8   360.0 175 3.15 3.440 17.02 0  0  3    2
Valiant             18.1 6   225.0 105 2.76 3.460 20.22 1  0  3    1
Duster 360          14.3 8   360.0 245 3.21 3.570 15.84 0  0  3    4
Merc 240D           24.4 4   146.7  62 3.69 3.190 20.00 1  0  4    2
Merc 230            22.8 4   140.8  95 3.92 3.150 22.90 1  0  4    2
Merc 280            19.2 6   167.6 123 3.92 3.440 18.30 1  0  4    4
Merc 280C           17.8 6   167.6 123 3.92 3.440 18.90 1  0  4    4
Merc 450SE          16.4 8   275.8 180 3.07 4.070 17.40 0  0  3    3
Merc 450SL          17.3 8   275.8 180 3.07 3.730 17.60 0  0  3    3
Merc 450SLC         15.2 8   275.8 180 3.07 3.780 18.00 0  0  3    3
Cadillac Fleetwood  10.4 8   472.0 205 2.93 5.250 17.98 0  0  3    4
Lincoln Continental 10.4 8   460.0 215 3.00 5.424 17.82 0  0  3    4
Chrysler Imperial   14.7 8   440.0 230 3.23 5.345 17.42 0  0  3    4
Fiat 128            32.4 4    78.7  66 4.08 2.200 19.47 1  1  4    1
Honda Civic         30.4 4    75.7  52 4.93 1.615 18.52 1  1  4    2
Toyota Corolla      33.9 4    71.1  65 4.22 1.835 19.90 1  1  4    1
Toyota Corona       21.5 4   120.1  97 3.70 2.465 20.01 1  0  3    1
Dodge Challenger    15.5 8   318.0 150 2.76 3.520 16.87 0  0  3    2
AMC Javelin         15.2 8   304.0 150 3.15 3.435 17.30 0  0  3    2
Camaro Z28          13.3 8   350.0 245 3.73 3.840 15.41 0  0  3    4
Pontiac Firebird    19.2 8   400.0 175 3.08 3.845 17.05 0  0  3    2
Fiat X1-9           27.3 4    79.0  66 4.08 1.935 18.90 1  1  4    1
Porsche 914-2       26.0 4   120.3  91 4.43 2.140 16.70 0  1  5    2
Lotus Europa        30.4 4    95.1 113 3.77 1.513 16.90 1  1  5    2
Ford Pantera L      15.8 8   351.0 264 4.22 3.170 14.50 0  1  5    4
Ferrari Dino        19.7 6   145.0 175 3.62 2.770 15.50 0  1  5    6
Maserati Bora       15.0 8   301.0 335 3.54 3.570 14.60 0  1  5    8
Volvo 142E          21.4 4   121.0 109 4.11 2.780 18.60 1  1  4    2

In [ ]:
help(mtcars) # Pode ser ?mtcars também

In [ ]:
class(mtcars)

[1] "data.frame"

In [ ]:
rownames(mtcars)

 [1] "Mazda RX4"           "Mazda RX4 Wag"       "Datsun 710"
 [4] "Hornet 4 Drive"      "Hornet Sportabout"   "Valiant"
 [7] "Duster 360"          "Merc 240D"           "Merc 230"
[10] "Merc 280"            "Merc 280C"           "Merc 450SE"
[13] "Merc 450SL"          "Merc 450SLC"         "Cadillac Fleetwood"
[16] "Lincoln Continental" "Chrysler Imperial"   "Fiat 128"
[19] "Honda Civic"         "Toyota Corolla"      "Toyota Corona"
[22] "Dodge Challenger"    "AMC Javelin"         "Camaro Z28"
[25] "Pontiac Firebird"    "Fiat X1-9"           "Porsche 914-2"
[28] "Lotus Europa"        "Ford Pantera L"      "Ferrari Dino"
[31] "Maserati Bora"       "Volvo 142E"

In [ ]:
colnames(mtcars)

 [1] "mpg"  "cyl"  "disp" "hp"   "drat" "wt"   "qsec" "vs"   "am"   "gear"
[11] "carb"

In [ ]:
names(mtcars)

 [1] "mpg"  "cyl"  "disp" "hp"   "drat" "wt"   "qsec" "vs"   "am"   "gear"
[11] "carb"

## Acessando colunas diretamente pelo nome
Usamos `$`. Por exemplo, para acessar a coluna `mpg` de `mtcars` usamos `mtcars$mpg`.

In [ ]:
mtcars

                    mpg  cyl disp  hp  drat wt    qsec  vs am gear carb
Mazda RX4           21.0 6   160.0 110 3.90 2.620 16.46 0  1  4    4
Mazda RX4 Wag       21.0 6   160.0 110 3.90 2.875 17.02 0  1  4    4
Datsun 710          22.8 4   108.0  93 3.85 2.320 18.61 1  1  4    1
Hornet 4 Drive      21.4 6   258.0 110 3.08 3.215 19.44 1  0  3    1
Hornet Sportabout   18.7 8   360.0 175 3.15 3.440 17.02 0  0  3    2
Valiant             18.1 6   225.0 105 2.76 3.460 20.22 1  0  3    1
Duster 360          14.3 8   360.0 245 3.21 3.570 15.84 0  0  3    4
Merc 240D           24.4 4   146.7  62 3.69 3.190 20.00 1  0  4    2
Merc 230            22.8 4   140.8  95 3.92 3.150 22.90 1  0  4    2
Merc 280            19.2 6   167.6 123 3.92 3.440 18.30 1  0  4    4
Merc 280C           17.8 6   167.6 123 3.92 3.440 18.90 1  0  4    4
Merc 450SE          16.4 8   275.8 180 3.07 4.070 17.40 0  0  3    3
Merc 450SL          17.3 8   275.8 180 3.07 3.730 17.60 0  0  3    3
Merc 450SLC         15.2 8   275.8 180 3.07 3.780 18.00 0  0  3    3
Cadillac Fleetwood  10.4 8   472.0 205 2.93 5.250 17.98 0  0  3    4
Lincoln Continental 10.4 8   460.0 215 3.00 5.424 17.82 0  0  3    4
Chrysler Imperial   14.7 8   440.0 230 3.23 5.345 17.42 0  0  3    4
Fiat 128            32.4 4    78.7  66 4.08 2.200 19.47 1  1  4    1
Honda Civic         30.4 4    75.7  52 4.93 1.615 18.52 1  1  4    2
Toyota Corolla      33.9 4    71.1  65 4.22 1.835 19.90 1  1  4    1
Toyota Corona       21.5 4   120.1  97 3.70 2.465 20.01 1  0  3    1
Dodge Challenger    15.5 8   318.0 150 2.76 3.520 16.87 0  0  3    2
AMC Javelin         15.2 8   304.0 150 3.15 3.435 17.30 0  0  3    2
Camaro Z28          13.3 8   350.0 245 3.73 3.840 15.41 0  0  3    4
Pontiac Firebird    19.2 8   400.0 175 3.08 3.845 17.05 0  0  3    2
Fiat X1-9           27.3 4    79.0  66 4.08 1.935 18.90 1  1  4    1
Porsche 914-2       26.0 4   120.3  91 4.43 2.140 16.70 0  1  5    2
Lotus Europa        30.4 4    95.1 113 3.77 1.513 16.90 1  1  5    2
Ford Pantera L      15.8 8   351.0 264 4.22 3.170 14.50 0  1  5    4
Ferrari Dino        19.7 6   145.0 175 3.62 2.770 15.50 0  1  5    6
Maserati Bora       15.0 8   301.0 335 3.54 3.570 14.60 0  1  5    8
Volvo 142E          21.4 4   121.0 109 4.11 2.780 18.60 1  1  4    2

In [ ]:
mtcars$gear

 [1] 4 4 4 3 3 3 3 4 4 4 4 3 3 3 3 3 3 4 4 4 3 3 3 3 3 4 5 5 5 5 5 4

In [ ]:
mtcars["gear"]

                    gear
Mazda RX4           4
Mazda RX4 Wag       4
Datsun 710          4
Hornet 4 Drive      3
Hornet Sportabout   3
Valiant             3
Duster 360          3
Merc 240D           4
Merc 230            4
Merc 280            4
Merc 280C           4
Merc 450SE          3
Merc 450SL          3
Merc 450SLC         3
Cadillac Fleetwood  3
Lincoln Continental 3
Chrysler Imperial   3
Fiat 128            4
Honda Civic         4
Toyota Corolla      4
Toyota Corona       3
Dodge Challenger    3
AMC Javelin         3
Camaro Z28          3
Pontiac Firebird    3
Fiat X1-9           4
Porsche 914-2       5
Lotus Europa        5
Ford Pantera L      5
Ferrari Dino        5
Maserati Bora       5
Volvo 142E          4

In [ ]:
mtcars$mpg

 [1] 21.0 21.0 22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2 17.8 16.4 17.3 15.2 10.4
[16] 10.4 14.7 32.4 30.4 33.9 21.5 15.5 15.2 13.3 19.2 27.3 26.0 30.4 15.8 19.7
[31] 15.0 21.4

In [ ]:
mean(mtcars$mpg)

[1] 20.09062

In [ ]:
class(mtcars$mpg)

[1] "numeric"

In [ ]:
iris

    Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1   5.1          3.5         1.4          0.2         setosa
2   4.9          3.0         1.4          0.2         setosa
3   4.7          3.2         1.3          0.2         setosa
4   4.6          3.1         1.5          0.2         setosa
5   5.0          3.6         1.4          0.2         setosa
6   5.4          3.9         1.7          0.4         setosa
7   4.6          3.4         1.4          0.3         setosa
8   5.0          3.4         1.5          0.2         setosa
9   4.4          2.9         1.4          0.2         setosa
10  4.9          3.1         1.5          0.1         setosa
11  5.4          3.7         1.5          0.2         setosa
12  4.8          3.4         1.6          0.2         setosa
13  4.8          3.0         1.4          0.1         setosa
14  4.3          3.0         1.1          0.1         setosa
15  5.8          4.0         1.2          0.2         setosa
16  5.7          4.4         1.5          0.4         setosa
17  5.4          3.9         1.3          0.4         setosa
18  5.1          3.5         1.4          0.3         setosa
19  5.7          3.8         1.7          0.3         setosa
20  5.1          3.8         1.5          0.3         setosa
21  5.4          3.4         1.7          0.2         setosa
22  5.1          3.7         1.5          0.4         setosa
23  4.6          3.6         1.0          0.2         setosa
24  5.1          3.3         1.7          0.5         setosa
25  4.8          3.4         1.9          0.2         setosa
26  5.0          3.0         1.6          0.2         setosa
27  5.0          3.4         1.6          0.4         setosa
28  5.2          3.5         1.5          0.2         setosa
29  5.2          3.4         1.4          0.2         setosa
30  4.7          3.2         1.6          0.2         setosa
⋮   ⋮            ⋮           ⋮            ⋮           ⋮
121 6.9          3.2         5.7          2.3         virginica
122 5.6          2.8         4.9          2.0         virginica
123 7.7          2.8         6.7          2.0         virginica
124 6.3          2.7         4.9          1.8         virginica
125 6.7          3.3         5.7          2.1         virginica
126 7.2          3.2         6.0          1.8         virginica
127 6.2          2.8         4.8          1.8         virginica
128 6.1          3.0         4.9          1.8         virginica
129 6.4          2.8         5.6          2.1         virginica
130 7.2          3.0         5.8          1.6         virginica
131 7.4          2.8         6.1          1.9         virginica
132 7.9          3.8         6.4          2.0         virginica
133 6.4          2.8         5.6          2.2         virginica
134 6.3          2.8         5.1          1.5         virginica
135 6.1          2.6         5.6          1.4         virginica
136 7.7          3.0         6.1          2.3         virginica
137 6.3          3.4         5.6          2.4         virginica
138 6.4          3.1         5.5          1.8         virginica
139 6.0          3.0         4.8          1.8         virginica
140 6.9          3.1         5.4          2.1         virginica
141 6.7          3.1         5.6          2.4         virginica
142 6.9          3.1         5.1          2.3         virginica
143 5.8          2.7         5.1          1.9         virginica
144 6.8          3.2         5.9          2.3         virginica
145 6.7          3.3         5.7          2.5         virginica
146 6.7          3.0         5.2          2.3         virginica
147 6.3          2.5         5.0          1.9         virginica
148 6.5          3.0         5.2          2.0         virginica
149 6.2          3.4         5.4          2.3         virginica
150 5.9          3.0         5.1          1.8         virginica

In [ ]:
help(iris)

In [ ]:
iris$Species

  [1] setosa     setosa     setosa     setosa     setosa     setosa
  [7] setosa     setosa     setosa     setosa     setosa     setosa
 [13] setosa     setosa     setosa     setosa     setosa     setosa
 [19] setosa     setosa     setosa     setosa     setosa     setosa
 [25] setosa     setosa     setosa     setosa     setosa     setosa
 [31] setosa     setosa     setosa     setosa     setosa     setosa
 [37] setosa     setosa     setosa     setosa     setosa     setosa
 [43] setosa     setosa     setosa     setosa     setosa     setosa
 [49] setosa     setosa     versicolor versicolor versicolor versicolor
 [55] versicolor versicolor versicolor versicolor versicolor versicolor
 [61] versicolor versicolor versicolor versicolor versicolor versicolor
 [67] versicolor versicolor versicolor versicolor versicolor versicolor
 [73] versicolor versicolor versicolor versicolor versicolor versicolor
 [79] versicolor versicolor versicolor versicolor versicolor versicolor
 [85] versicolor versicolor versicolor versicolor versicolor versicolor
 [91] versicolor versicolor versicolor versicolor versicolor versicolor
 [97] versicolor versicolor versicolor versicolor virginica  virginica
[103] virginica  virginica  virginica  virginica  virginica  virginica
[109] virginica  virginica  virginica  virginica  virginica  virginica
[115] virginica  virginica  virginica  virginica  virginica  virginica
[121] virginica  virginica  virginica  virginica  virginica  virginica
[127] virginica  virginica  virginica  virginica  virginica  virginica
[133] virginica  virginica  virginica  virginica  virginica  virginica
[139] virginica  virginica  virginica  virginica  virginica  virginica
[145] virginica  virginica  virginica  virginica  virginica  virginica
Levels: setosa versicolor virginica

## Coordenadas em data frames
Sendo `df` um data frame, `df[linha, coluna]` nos dá o elemento da linha `linha` e coluna `coluna`. Lembre que no R começamos a contar de 1.

In [ ]:
mtcars

                    mpg  cyl disp  hp  drat wt    qsec  vs am gear carb
Mazda RX4           21.0 6   160.0 110 3.90 2.620 16.46 0  1  4    4
Mazda RX4 Wag       21.0 6   160.0 110 3.90 2.875 17.02 0  1  4    4
Datsun 710          22.8 4   108.0  93 3.85 2.320 18.61 1  1  4    1
Hornet 4 Drive      21.4 6   258.0 110 3.08 3.215 19.44 1  0  3    1
Hornet Sportabout   18.7 8   360.0 175 3.15 3.440 17.02 0  0  3    2
Valiant             18.1 6   225.0 105 2.76 3.460 20.22 1  0  3    1
Duster 360          14.3 8   360.0 245 3.21 3.570 15.84 0  0  3    4
Merc 240D           24.4 4   146.7  62 3.69 3.190 20.00 1  0  4    2
Merc 230            22.8 4   140.8  95 3.92 3.150 22.90 1  0  4    2
Merc 280            19.2 6   167.6 123 3.92 3.440 18.30 1  0  4    4
Merc 280C           17.8 6   167.6 123 3.92 3.440 18.90 1  0  4    4
Merc 450SE          16.4 8   275.8 180 3.07 4.070 17.40 0  0  3    3
Merc 450SL          17.3 8   275.8 180 3.07 3.730 17.60 0  0  3    3
Merc 450SLC         15.2 8   275.8 180 3.07 3.780 18.00 0  0  3    3
Cadillac Fleetwood  10.4 8   472.0 205 2.93 5.250 17.98 0  0  3    4
Lincoln Continental 10.4 8   460.0 215 3.00 5.424 17.82 0  0  3    4
Chrysler Imperial   14.7 8   440.0 230 3.23 5.345 17.42 0  0  3    4
Fiat 128            32.4 4    78.7  66 4.08 2.200 19.47 1  1  4    1
Honda Civic         30.4 4    75.7  52 4.93 1.615 18.52 1  1  4    2
Toyota Corolla      33.9 4    71.1  65 4.22 1.835 19.90 1  1  4    1
Toyota Corona       21.5 4   120.1  97 3.70 2.465 20.01 1  0  3    1
Dodge Challenger    15.5 8   318.0 150 2.76 3.520 16.87 0  0  3    2
AMC Javelin         15.2 8   304.0 150 3.15 3.435 17.30 0  0  3    2
Camaro Z28          13.3 8   350.0 245 3.73 3.840 15.41 0  0  3    4
Pontiac Firebird    19.2 8   400.0 175 3.08 3.845 17.05 0  0  3    2
Fiat X1-9           27.3 4    79.0  66 4.08 1.935 18.90 1  1  4    1
Porsche 914-2       26.0 4   120.3  91 4.43 2.140 16.70 0  1  5    2
Lotus Europa        30.4 4    95.1 113 3.77 1.513 16.90 1  1  5    2
Ford Pantera L      15.8 8   351.0 264 4.22 3.170 14.50 0  1  5    4
Ferrari Dino        19.7 6   145.0 175 3.62 2.770 15.50 0  1  5    6
Maserati Bora       15.0 8   301.0 335 3.54 3.570 14.60 0  1  5    8
Volvo 142E          21.4 4   121.0 109 4.11 2.780 18.60 1  1  4    2

In [ ]:
# linha 1, coluna 2
mtcars[1,2]  # Note que os nomes das linhas não contam como coluna

[1] 6

In [ ]:
# Acessando pelos nomes
mtcars["Fiat 128", "cyl"]

[1] 4

In [ ]:
# Se não colocar vírgula no meio, o R entende coluna
mtcars[1]    # Primeira coluna

                    mpg
Mazda RX4           21.0
Mazda RX4 Wag       21.0
Datsun 710          22.8
Hornet 4 Drive      21.4
Hornet Sportabout   18.7
Valiant             18.1
Duster 360          14.3
Merc 240D           24.4
Merc 230            22.8
Merc 280            19.2
Merc 280C           17.8
Merc 450SE          16.4
Merc 450SL          17.3
Merc 450SLC         15.2
Cadillac Fleetwood  10.4
Lincoln Continental 10.4
Chrysler Imperial   14.7
Fiat 128            32.4
Honda Civic         30.4
Toyota Corolla      33.9
Toyota Corona       21.5
Dodge Challenger    15.5
AMC Javelin         15.2
Camaro Z28          13.3
Pontiac Firebird    19.2
Fiat X1-9           27.3
Porsche 914-2       26.0
Lotus Europa        30.4
Ford Pantera L      15.8
Ferrari Dino        19.7
Maserati Bora       15.0
Volvo 142E          21.4

In [ ]:
mtcars[1,]

          mpg cyl disp hp  drat wt   qsec  vs am gear carb
Mazda RX4 21  6   160  110 3.9  2.62 16.46 0  1  4    4

In [ ]:
# Qual é a diferença?
mtcars[,2]

 [1] 6 6 4 6 8 6 8 4 4 6 6 8 8 8 8 8 8 4 4 4 4 8 8 8 8 4 4 4 8 6 8 4

In [ ]:
mtcars[2]

In [ ]:
mtcars[c(1,2)]

                    mpg  cyl
Mazda RX4           21.0 6
Mazda RX4 Wag       21.0 6
Datsun 710          22.8 4
Hornet 4 Drive      21.4 6
Hornet Sportabout   18.7 8
Valiant             18.1 6
Duster 360          14.3 8
Merc 240D           24.4 4
Merc 230            22.8 4
Merc 280            19.2 6
Merc 280C           17.8 6
Merc 450SE          16.4 8
Merc 450SL          17.3 8
Merc 450SLC         15.2 8
Cadillac Fleetwood  10.4 8
Lincoln Continental 10.4 8
Chrysler Imperial   14.7 8
Fiat 128            32.4 4
Honda Civic         30.4 4
Toyota Corolla      33.9 4
Toyota Corona       21.5 4
Dodge Challenger    15.5 8
AMC Javelin         15.2 8
Camaro Z28          13.3 8
Pontiac Firebird    19.2 8
Fiat X1-9           27.3 4
Porsche 914-2       26.0 4
Lotus Europa        30.4 4
Ford Pantera L      15.8 8
Ferrari Dino        19.7 6
Maserati Bora       15.0 8
Volvo 142E          21.4 4

In [ ]:
mtcars[1:3, 2:6]

              cyl disp hp  drat wt
Mazda RX4     6   160  110 3.90 2.620
Mazda RX4 Wag 6   160  110 3.90 2.875
Datsun 710    4   108   93 3.85 2.320

In [ ]:
mtcars[1:3, c(2,4)]

              cyl hp
Mazda RX4     6   110
Mazda RX4 Wag 6   110
Datsun 710    4    93

In [ ]:
mtcars[1:3]

In [ ]:
# Qual é a diferença?
mtcars[c(1,2,4)]

In [ ]:
mtcars

In [ ]:
mtcars[1:4,1:3] # Linhas 1 e 4, colunas de 1 a 3

In [ ]:
mtcars[1:4,]

In [ ]:
mtcars[1:10, c("mpg", "cyl", "vs")]

In [ ]:
# Voltando a usar vírgula
mtcars[1,] # Primeira linha

In [ ]:
mtcars[,1] # Primeira coluna (vetor)

In [ ]:
mtcars[1] # Coluna 1 (data frame)

In [ ]:
class(mtcars[1])

In [ ]:
class(mtcars[,1])

## Juntando tudo: filtros e data frames
Podemos usar filtros lógicos para escolher elementos que satisfazem critérios em data frames

In [ ]:
mtcars

                    mpg  cyl disp  hp  drat wt    qsec  vs am gear carb
Mazda RX4           21.0 6   160.0 110 3.90 2.620 16.46 0  1  4    4
Mazda RX4 Wag       21.0 6   160.0 110 3.90 2.875 17.02 0  1  4    4
Datsun 710          22.8 4   108.0  93 3.85 2.320 18.61 1  1  4    1
Hornet 4 Drive      21.4 6   258.0 110 3.08 3.215 19.44 1  0  3    1
Hornet Sportabout   18.7 8   360.0 175 3.15 3.440 17.02 0  0  3    2
Valiant             18.1 6   225.0 105 2.76 3.460 20.22 1  0  3    1
Duster 360          14.3 8   360.0 245 3.21 3.570 15.84 0  0  3    4
Merc 240D           24.4 4   146.7  62 3.69 3.190 20.00 1  0  4    2
Merc 230            22.8 4   140.8  95 3.92 3.150 22.90 1  0  4    2
Merc 280            19.2 6   167.6 123 3.92 3.440 18.30 1  0  4    4
Merc 280C           17.8 6   167.6 123 3.92 3.440 18.90 1  0  4    4
Merc 450SE          16.4 8   275.8 180 3.07 4.070 17.40 0  0  3    3
Merc 450SL          17.3 8   275.8 180 3.07 3.730 17.60 0  0  3    3
Merc 450SLC         15.2 8   275.8 180 3.07 3.780 18.00 0  0  3    3
Cadillac Fleetwood  10.4 8   472.0 205 2.93 5.250 17.98 0  0  3    4
Lincoln Continental 10.4 8   460.0 215 3.00 5.424 17.82 0  0  3    4
Chrysler Imperial   14.7 8   440.0 230 3.23 5.345 17.42 0  0  3    4
Fiat 128            32.4 4    78.7  66 4.08 2.200 19.47 1  1  4    1
Honda Civic         30.4 4    75.7  52 4.93 1.615 18.52 1  1  4    2
Toyota Corolla      33.9 4    71.1  65 4.22 1.835 19.90 1  1  4    1
Toyota Corona       21.5 4   120.1  97 3.70 2.465 20.01 1  0  3    1
Dodge Challenger    15.5 8   318.0 150 2.76 3.520 16.87 0  0  3    2
AMC Javelin         15.2 8   304.0 150 3.15 3.435 17.30 0  0  3    2
Camaro Z28          13.3 8   350.0 245 3.73 3.840 15.41 0  0  3    4
Pontiac Firebird    19.2 8   400.0 175 3.08 3.845 17.05 0  0  3    2
Fiat X1-9           27.3 4    79.0  66 4.08 1.935 18.90 1  1  4    1
Porsche 914-2       26.0 4   120.3  91 4.43 2.140 16.70 0  1  5    2
Lotus Europa        30.4 4    95.1 113 3.77 1.513 16.90 1  1  5    2
Ford Pantera L      15.8 8   351.0 264 4.22 3.170 14.50 0  1  5    4
Ferrari Dino        19.7 6   145.0 175 3.62 2.770 15.50 0  1  5    6
Maserati Bora       15.0 8   301.0 335 3.54 3.570 14.60 0  1  5    8
Volvo 142E          21.4 4   121.0 109 4.11 2.780 18.60 1  1  4    2

In [ ]:
mtcars$mpg

 [1] 21.0 21.0 22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2 17.8 16.4 17.3 15.2 10.4
[16] 10.4 14.7 32.4 30.4 33.9 21.5 15.5 15.2 13.3 19.2 27.3 26.0 30.4 15.8 19.7
[31] 15.0 21.4

In [ ]:
mtcars$cyl # Coluna cyl, na forma de vetor

In [ ]:
mtcars$cyl == 4

In [ ]:
as.numeric(mtcars$cyl == 4)

In [ ]:
sum(mtcars$cyl == 4)

In [ ]:
# Filtrando os carros com 4 cilindros (cyl==4)
mtcars[mtcars$cyl == 4, ] # Não se esqueça da vírgula!

In [ ]:
# Filtre os carros com mpg > 20!
mtcars[mtcars$mpg > 25, ]

In [ ]:
mtcars[mtcars[2] == 4,]

In [ ]:
# km/l
mtcars$mpg*0.425144

In [ ]:
mtcars[mtcars$mpg > 25, c("cyl", "mpg")]

In [ ]:
dados <- mtcars

In [ ]:
# Dá para fazer os dois filtros ao mesmo tempo?
mtcars[mtcars$cyl==4 & mtcars$mpg>25, ]

In [ ]:
iris

In [ ]:
iris[iris$Sepal.Length > 7,]

In [ ]:
# Dá para ranquear os carros de acordo com o consumo?
mtcars$mpg

In [ ]:
sort(mtcars$mpg, decreasing=TRUE)

In [ ]:
order(mtcars$mpg, decreasing=TRUE)

In [ ]:
mtcars[sort(mtcars$mpg, decreasing=TRUE), ]

In [ ]:
mtcars[20,]

In [ ]:
mtcars[order(mtcars$mpg, decreasing=TRUE),]

# Exercícios: data frames
1. Experimente os seguintes comandos e veja quais dão um vetor com a coluna `mpg` do `mtcars`.

> a) `mtcars$mpg`

> b) `mtcars[ , 3]`

> c) `mtcars("mpg")`

> d) `mtcars[ , "mpg"]`

> e) `mtcars.mpg`

> f) `mtcars[ , 1]`

> g) `mtcars[1, 1]`

> h) `mpg$mtcars`

In [ ]:
# Exercício 1
mtcars$mpg

In [ ]:
mtcars[ , 1]

In [ ]:
mtcars("mpg")

In [ ]:
mtcars["mpg"]

In [ ]:
mtcars.mpg

In [ ]:
mpg$mtcars

2. Use a função `str()`. O que ela faz? Lembre que você pode fazer `?str`.

In [ ]:
# Exercício 2
str(iris)

3. E a função `names`, para que serve?

In [ ]:
# Exercício 3
names(mtcars)   # nomes das colunas (variáveis)

4. Mais um data frame que vem com o R: `airquality`.

> a) Quantas linhas e colunas tem?

> b) Use a função `head()` nele. O que essa função faz?

> c) Encontre os nomes das colunas.

> d) Qual é a classe da coluna `Ozone`?

In [ ]:
# Exercício 4
dim(airquality)

In [ ]:
airquality

In [ ]:
head(airquality)

In [ ]:
tail(airquality)

In [ ]:
names(airquality)

In [ ]:
class(airquality$Ozone)

5. Ainda sobre o data frame `airquality`:

> a) Quantos `NA`s tem a coluna `Solar.R`?

> b) Exiba as linhas em que `Solar.R` é `NA`.

> c) Exiba as linhas em que `Solar.R` não é `NA`.

In [ ]:
dados.com.NA = c(NA,1,2,4,NA)
dados.com.NA == NA
is.na(dados.com.NA)
sum(is.na(dados.com.NA))

In [ ]:
airquality$Solar.R

In [ ]:
is.na(airquality$Solar.R)

In [ ]:
# is.na verifica se é NA; depois soma
sum(is.na(airquality$Solar.R))

In [ ]:
# Exercício 5
airquality[is.na(airquality$Solar.R),]

In [ ]:
airquality[!is.na(airquality$Solar.R),]

## Funções
* Já usamos algumas: `sqrt()`, `class()`, `c()`, `paste()`, `gsub()`...
* Formato: `nome_da_funcao(arg1, arg2, ..., argk)`
* Separamos argumentos por vírgula!
* Algumas usam vetor como argumento

In [ ]:
sum(c(1,2))

In [ ]:
sum(c(1,2),c(3,4))

In [ ]:
mean(c(1,2))

In [ ]:
mean(c(1,2),3)

In [ ]:
# Média do mpg do mtcars?
mean(mtcars$mpg)

In [ ]:
# E se tiver NA?
mean(c(1,3,NA))

In [ ]:
mean(airquality$Ozone)

In [ ]:
# Como lidar com isso? Argumento opcional: na.rm=TRUE
mean(c(1,3,NA), na.rm=TRUE)

In [ ]:
mean(airquality$Ozone, na.rm=TRUE)

In [ ]:
?mean

## A função `seq()`
Para sequências aritméticas

In [ ]:
seq(from=4, to=10, by=2)

In [ ]:
seq(4, 10, 2)

In [ ]:
seq(by=2, to=10, from=4)

In [ ]:
seq(2,10,4)

## Funções para data frames
* `head()`: seis primeiras linhas
* `tail()`: seis últimas linhas (bom para ver se os últimos dados entraram no data frame)
* `dim()`: número de linhas e colunas
* `names()`: nomes das variáveis (colunas)
* `str()`: estrutura do data frame
* `cbind()`: junta tabelas lado a lado (`c` = column)
* `rbind()`: junta tabelas uma sobre a outra (`r` = row)

In [ ]:
str(iris)

In [ ]:
names(iris)

In [ ]:
head(iris)

In [ ]:
tail(iris)

In [ ]:
dim(iris)

In [ ]:
tabela <- mtcars
rbind(tabela,tabela)
tabela2 <- iris
cbind(tabela2,tabela2)

# Criando nossas próprias funções
Podemos criar funções! A sintaxe é
```
nome_da_funcao <- function(arg1, arg2, ..., argk){
   # tarefa a ser realizada
}
```

In [ ]:
# Função que calcula a soma de dois números
minha_soma <- function(x,y){
  soma <- x+y
  soma
}

In [ ]:
class(minha_soma)

In [ ]:
minha_soma(2,3)

In [ ]:
minha_soma(c(1,2),c(3,4))

In [ ]:
c(1,2) + c(3,4)

In [ ]:
# Podemos usar return para explicitar o que deve ser retornado
minha_soma2 <- function(x,y){
  return(x+y)
}

In [ ]:
minha_soma2(c(3,4),c(1,5))

In [ ]:
# Posso colocar em um objeto?
resultado <- minha_soma(3,4)

In [ ]:
resultado

## Variáveis locais e globais
O `x` e o `y` dentro de `minha_soma` são _locais_, ou seja, só existem dentro da função. Quando a função terminou de rodar, `x` e `y` somem.

In [ ]:
# Vai dar erro
soma

In [ ]:
porcento <- function(valor, porc){
  return(valor*porc/100)
}

In [ ]:
porcento(11000,20)

## Mais sobre funções
* Curso online: https://livro.curso-r.com/3-11-maisFuncoes.html#exerc%C3%ADcios-7
* Aprofundamento: https://bookdown.org/rdpeng/rprogdatascience/functions.html#functions-in-r

(No aprofundamento tem loops, que vamos aprender mais tarde)

## Exercícios sobre funções
1. Crie uma função que receba um número e retorne o quadrado deste número.

In [ ]:
# Exercício 1
quadrado <- function(x){
  return(x*x)
}

In [ ]:
quadrado(8)

2. Crie uma função que receba 2 números e devolva a raiz quadrada da soma desses números.

In [ ]:
# Exercício 2
receba <- function(x,y){
  return(sqrt(x+y))
}

In [ ]:
receba(1,7)

3. Rode `help(sample)` para descobrir o que a função `sample()` faz. Em seguida

> a) use-a para escrever uma função que devolva uma linha aleatória de um dataframe;

> b) generalize a função para retornar um número qualquer de linhas, que poderá ser escolhido por quem for usá-la.

In [ ]:
# Exercício 3
?sample

In [ ]:
sample(60, 6)

In [ ]:
sample(6, 100, replace=TRUE)

In [ ]:
mtcars

In [ ]:
nrow(mtcars)

In [ ]:
ncol(mtcars)

In [ ]:
sample(nrow(mtcars),1)

In [ ]:
mtcars[8,]

In [ ]:
mtcars[sample(nrow(mtcars),1),]

In [ ]:
sorteia <- function(df){
  return(df[sample(nrow(df),1),])
}

In [ ]:
sorteia(iris)

# Controle de fluxo (loops, se-então-senão)
O R também aceita loops (`if`, `else`, `for`, `while`)

Veja mais em:
* https://livro.curso-r.com/3-12-controle-de-fluxo.html#controle-de-fluxo
* https://bookdown.org/rdpeng/rprogdatascience/control-structures.html

Os loops listados acima costumam ser lentos. Em geral usamos as funções `*apply`. Veja mais em https://bookdown.org/rdpeng/rprogdatascience/loop-functions.html

## `if` e `else`
Sintaxe:
```
if(condição){
  # faça coisas
}
else{
  # faça outras coisas
}
```

In [ ]:
x <- 2

if(x == 1){
  Sys.time()   # Coloca hora e data na tela
}

In [ ]:
x <- 1

if(x == 1){
  Sys.time()   # Coloca hora e data na tela
}

Podemos adaptar a função `minha_soma()` para tratar erros.

In [ ]:
minha_soma <- function(x, y) {
  if (class(x) == "numeric" & class(y) == "numeric") {
     x + y
  }
}

In [ ]:
minha_soma(3,2)

In [ ]:
minha_soma("a",2)

## Exercícios
1. Faça uma função que multiplique dois números e coloque na tela uma mensagem de erro personalizada quando algum dos dois números não é da classe `numeric`.

In [ ]:
# Solução

In [ ]:
# Testes

2. Crie um script que pega um `nome` como argumento e retorna `Olá nome!`.

In [ ]:
# Solução

In [ ]:
# Testes

3. Crie uma função que recebe três inteiros e retorna sua soma. Porém, quando algum valor é divisível por 3 o mesmo não é considerado na soma. Casos todos os três sejam divisíveis por 3 a soma deve resultar em 0.

In [ ]:
# Solução

In [ ]:
# Testes

## Usando `else`

In [ ]:
x <- c(1, 3, 10, 15)

if (class(x) == "numeric") {
  sum(x)
} else {
  NA
}

In [ ]:
x <- c(1, 3, 10, "15")

if (class(x) == "numeric") {
  sum(x)
} else {
  NA
}

In [ ]:
x <- 0

if(x < 0) {
  "negativo"
} else if(x == 0) {
  "neutro"
} else if(x > 0) {
  "positivo"
}

## `return()` e `stop()`
* `return()` sai da função imediatamente com a resposta (dentro do `return`).
* `stop()` sai da função imediatamente e coloca mensagem de erro (dentro do `stop`).

In [ ]:
minha_soma_NA <- function(x, y) {
  if (class(x) == "numeric" & class(y) == "numeric") {
     soma <- x + y
     return(soma)
  }
  NA
}

In [ ]:
minha_soma_NA(1, 2)

In [ ]:
minha_soma_NA("a", "b")

In [ ]:
minha_soma_NA(1, "b")

In [ ]:
minha_soma_erro <- function(x, y) {
  if (class(x) != "numeric" | class(y) != "numeric") {
    stop("A classe dos objetos x e y deve ser numérica.")
  }
  x + y
}

In [ ]:
minha_soma_erro(1, 2)

In [ ]:
minha_soma_erro("a", "b")

In [ ]:
minha_soma_erro(1, "b")

## `for`
Sintaxe:
```
for(indice in vetor){
  # Faça coisas
}
```

In [ ]:
numero_de_colunas <- ncol(mtcars)

for (coluna in 1:numero_de_colunas) {
  media <- mean(mtcars[,coluna])

  print(media)
}

In [ ]:
numero_de_colunas <- ncol(mtcars)

# Antes, criamos um vetor vazio.
medias <- c()

for (coluna in 1:numero_de_colunas) {
  medias[coluna] <- mean(mtcars[,coluna])
}

medias

In [ ]:
# A função colMeans() faz isso sem loops!
colMeans(mtcars)

## `while`
Sintaxe:
```
while(condição){
  # Faça coisas
}
```

In [ ]:
i <- 1

while (i < 3){
  print(i)
  i <-  i + 1
}

## Exercício
Utilize o vetor `a` para resolver as questões a seguir:
```
a <- c(10, 3, 5, -1, 3, -4, 8, 9, -10)
```
> a) Utilize o `for` para imprimir as médias acumuladas do vetor `a`, isto é, primeiro vamos imprimir 10, depois a média entre 10 e 3, depois a média entre 10, 3 e 5 e assim por diante.

> b) Adapte o laço que você fez no item anterior para ignorar os valores negativos, isto é, em caso de valor negativo, o laço não deve calcular a média e não imprimir nada.