Data Frames - conjunto

In [ ]:
mtcars

                    mpg  cyl disp  hp  drat wt    qsec  vs am gear carb
Mazda RX4           21.0 6   160.0 110 3.90 2.620 16.46 0  1  4    4
Mazda RX4 Wag       21.0 6   160.0 110 3.90 2.875 17.02 0  1  4    4
Datsun 710          22.8 4   108.0  93 3.85 2.320 18.61 1  1  4    1
Hornet 4 Drive      21.4 6   258.0 110 3.08 3.215 19.44 1  0  3    1
Hornet Sportabout   18.7 8   360.0 175 3.15 3.440 17.02 0  0  3    2
Valiant             18.1 6   225.0 105 2.76 3.460 20.22 1  0  3    1
Duster 360          14.3 8   360.0 245 3.21 3.570 15.84 0  0  3    4
Merc 240D           24.4 4   146.7  62 3.69 3.190 20.00 1  0  4    2
Merc 230            22.8 4   140.8  95 3.92 3.150 22.90 1  0  4    2
Merc 280            19.2 6   167.6 123 3.92 3.440 18.30 1  0  4    4
Merc 280C           17.8 6   167.6 123 3.92 3.440 18.90 1  0  4    4
Merc 450SE          16.4 8   275.8 180 3.07 4.070 17.40 0  0  3    3
Merc 450SL          17.3 8   275.8 180 3.07 3.730 17.60 0  0  3    3
Merc 450SLC         15.2 8   275.8 180 3.07 3.780 18.00 0  0  3    3
Cadillac Fleetwood  10.4 8   472.0 205 2.93 5.250 17.98 0  0  3    4
Lincoln Continental 10.4 8   460.0 215 3.00 5.424 17.82 0  0  3    4
Chrysler Imperial   14.7 8   440.0 230 3.23 5.345 17.42 0  0  3    4
Fiat 128            32.4 4    78.7  66 4.08 2.200 19.47 1  1  4    1
Honda Civic         30.4 4    75.7  52 4.93 1.615 18.52 1  1  4    2
Toyota Corolla      33.9 4    71.1  65 4.22 1.835 19.90 1  1  4    1
Toyota Corona       21.5 4   120.1  97 3.70 2.465 20.01 1  0  3    1
Dodge Challenger    15.5 8   318.0 150 2.76 3.520 16.87 0  0  3    2
AMC Javelin         15.2 8   304.0 150 3.15 3.435 17.30 0  0  3    2
Camaro Z28          13.3 8   350.0 245 3.73 3.840 15.41 0  0  3    4
Pontiac Firebird    19.2 8   400.0 175 3.08 3.845 17.05 0  0  3    2
Fiat X1-9           27.3 4    79.0  66 4.08 1.935 18.90 1  1  4    1
Porsche 914-2       26.0 4   120.3  91 4.43 2.140 16.70 0  1  5    2
Lotus Europa        30.4 4    95.1 113 3.77 1.513 16.90 1  1  5    2
Ford Pantera L      15.8 8   351.0 264 4.22 3.170 14.50 0  1  5    4
Ferrari Dino        19.7 6   145.0 175 3.62 2.770 15.50 0  1  5    6
Maserati Bora       15.0 8   301.0 335 3.54 3.570 14.60 0  1  5    8
Volvo 142E          21.4 4   121.0 109 4.11 2.780 18.60 1  1  4    2

In [ ]:
help(mtcars)

In [ ]:
# lógico, caracter, numeric, data frame
class(mtcars)
class(1)
class(TRUE)
class("tinha")

[1] "data.frame"

[1] "numeric"

[1] "logical"

[1] "character"

In [ ]:
row.names(mtcars)

 [1] "Mazda RX4"           "Mazda RX4 Wag"       "Datsun 710"
 [4] "Hornet 4 Drive"      "Hornet Sportabout"   "Valiant"
 [7] "Duster 360"          "Merc 240D"           "Merc 230"
[10] "Merc 280"            "Merc 280C"           "Merc 450SE"
[13] "Merc 450SL"          "Merc 450SLC"         "Cadillac Fleetwood"
[16] "Lincoln Continental" "Chrysler Imperial"   "Fiat 128"
[19] "Honda Civic"         "Toyota Corolla"      "Toyota Corona"
[22] "Dodge Challenger"    "AMC Javelin"         "Camaro Z28"
[25] "Pontiac Firebird"    "Fiat X1-9"           "Porsche 914-2"
[28] "Lotus Europa"        "Ford Pantera L"      "Ferrari Dino"
[31] "Maserati Bora"       "Volvo 142E"

In [ ]:
# Colunas
colnames(mtcars)

 [1] "mpg"  "cyl"  "disp" "hp"   "drat" "wt"   "qsec" "vs"   "am"   "gear"
[11] "carb"

In [ ]:
# Data frame - nomes das colunas
names(mtcars)

 [1] "mpg"  "cyl"  "disp" "hp"   "drat" "wt"   "qsec" "vs"   "am"   "gear"
[11] "carb"

In [ ]:
# coluna mpg
mtcars$mpg
class(mtcars$am)

 [1] 21.0 21.0 22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2 17.8 16.4 17.3 15.2 10.4
[16] 10.4 14.7 32.4 30.4 33.9 21.5 15.5 15.2 13.3 19.2 27.3 26.0 30.4 15.8 19.7
[31] 15.0 21.4

[1] "numeric"

In [ ]:
iris

    Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1   5.1          3.5         1.4          0.2         setosa
2   4.9          3.0         1.4          0.2         setosa
3   4.7          3.2         1.3          0.2         setosa
4   4.6          3.1         1.5          0.2         setosa
5   5.0          3.6         1.4          0.2         setosa
6   5.4          3.9         1.7          0.4         setosa
7   4.6          3.4         1.4          0.3         setosa
8   5.0          3.4         1.5          0.2         setosa
9   4.4          2.9         1.4          0.2         setosa
10  4.9          3.1         1.5          0.1         setosa
11  5.4          3.7         1.5          0.2         setosa
12  4.8          3.4         1.6          0.2         setosa
13  4.8          3.0         1.4          0.1         setosa
14  4.3          3.0         1.1          0.1         setosa
15  5.8          4.0         1.2          0.2         setosa
16  5.7          4.4         1.5          0.4         setosa
17  5.4          3.9         1.3          0.4         setosa
18  5.1          3.5         1.4          0.3         setosa
19  5.7          3.8         1.7          0.3         setosa
20  5.1          3.8         1.5          0.3         setosa
21  5.4          3.4         1.7          0.2         setosa
22  5.1          3.7         1.5          0.4         setosa
23  4.6          3.6         1.0          0.2         setosa
24  5.1          3.3         1.7          0.5         setosa
25  4.8          3.4         1.9          0.2         setosa
26  5.0          3.0         1.6          0.2         setosa
27  5.0          3.4         1.6          0.4         setosa
28  5.2          3.5         1.5          0.2         setosa
29  5.2          3.4         1.4          0.2         setosa
30  4.7          3.2         1.6          0.2         setosa
⋮   ⋮            ⋮           ⋮            ⋮           ⋮
121 6.9          3.2         5.7          2.3         virginica
122 5.6          2.8         4.9          2.0         virginica
123 7.7          2.8         6.7          2.0         virginica
124 6.3          2.7         4.9          1.8         virginica
125 6.7          3.3         5.7          2.1         virginica
126 7.2          3.2         6.0          1.8         virginica
127 6.2          2.8         4.8          1.8         virginica
128 6.1          3.0         4.9          1.8         virginica
129 6.4          2.8         5.6          2.1         virginica
130 7.2          3.0         5.8          1.6         virginica
131 7.4          2.8         6.1          1.9         virginica
132 7.9          3.8         6.4          2.0         virginica
133 6.4          2.8         5.6          2.2         virginica
134 6.3          2.8         5.1          1.5         virginica
135 6.1          2.6         5.6          1.4         virginica
136 7.7          3.0         6.1          2.3         virginica
137 6.3          3.4         5.6          2.4         virginica
138 6.4          3.1         5.5          1.8         virginica
139 6.0          3.0         4.8          1.8         virginica
140 6.9          3.1         5.4          2.1         virginica
141 6.7          3.1         5.6          2.4         virginica
142 6.9          3.1         5.1          2.3         virginica
143 5.8          2.7         5.1          1.9         virginica
144 6.8          3.2         5.9          2.3         virginica
145 6.7          3.3         5.7          2.5         virginica
146 6.7          3.0         5.2          2.3         virginica
147 6.3          2.5         5.0          1.9         virginica
148 6.5          3.0         5.2          2.0         virginica
149 6.2          3.4         5.4          2.3         virginica
150 5.9          3.0         5.1          1.8         virginica

In [ ]:
help(iris)

In [ ]:
iris$Species

  [1] setosa     setosa     setosa     setosa     setosa     setosa
  [7] setosa     setosa     setosa     setosa     setosa     setosa
 [13] setosa     setosa     setosa     setosa     setosa     setosa
 [19] setosa     setosa     setosa     setosa     setosa     setosa
 [25] setosa     setosa     setosa     setosa     setosa     setosa
 [31] setosa     setosa     setosa     setosa     setosa     setosa
 [37] setosa     setosa     setosa     setosa     setosa     setosa
 [43] setosa     setosa     setosa     setosa     setosa     setosa
 [49] setosa     setosa     versicolor versicolor versicolor versicolor
 [55] versicolor versicolor versicolor versicolor versicolor versicolor
 [61] versicolor versicolor versicolor versicolor versicolor versicolor
 [67] versicolor versicolor versicolor versicolor versicolor versicolor
 [73] versicolor versicolor versicolor versicolor versicolor versicolor
 [79] versicolor versicolor versicolor versicolor versicolor versicolor
 [85] versicolor versicolor versicolor versicolor versicolor versicolor
 [91] versicolor versicolor versicolor versicolor versicolor versicolor
 [97] versicolor versicolor versicolor versicolor virginica  virginica
[103] virginica  virginica  virginica  virginica  virginica  virginica
[109] virginica  virginica  virginica  virginica  virginica  virginica
[115] virginica  virginica  virginica  virginica  virginica  virginica
[121] virginica  virginica  virginica  virginica  virginica  virginica
[127] virginica  virginica  virginica  virginica  virginica  virginica
[133] virginica  virginica  virginica  virginica  virginica  virginica
[139] virginica  virginica  virginica  virginica  virginica  virginica
[145] virginica  virginica  virginica  virginica  virginica  virginica
Levels: setosa versicolor virginica

In [ ]:
iris$Petal.Length

  [1] 1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 1.5 1.6 1.4 1.1 1.2 1.5 1.3 1.4
 [19] 1.7 1.5 1.7 1.5 1.0 1.7 1.9 1.6 1.6 1.5 1.4 1.6 1.6 1.5 1.5 1.4 1.5 1.2
 [37] 1.3 1.4 1.3 1.5 1.3 1.3 1.3 1.6 1.9 1.4 1.6 1.4 1.5 1.4 4.7 4.5 4.9 4.0
 [55] 4.6 4.5 4.7 3.3 4.6 3.9 3.5 4.2 4.0 4.7 3.6 4.4 4.5 4.1 4.5 3.9 4.8 4.0
 [73] 4.9 4.7 4.3 4.4 4.8 5.0 4.5 3.5 3.8 3.7 3.9 5.1 4.5 4.5 4.7 4.4 4.1 4.0
 [91] 4.4 4.6 4.0 3.3 4.2 4.2 4.2 4.3 3.0 4.1 6.0 5.1 5.9 5.6 5.8 6.6 4.5 6.3
[109] 5.8 6.1 5.1 5.3 5.5 5.0 5.1 5.3 5.5 6.7 6.9 5.0 5.7 4.9 6.7 4.9 5.7 6.0
[127] 4.8 4.9 5.6 5.8 6.1 6.4 5.6 5.1 5.6 6.1 5.6 5.5 4.8 5.4 5.6 5.1 5.1 5.9
[145] 5.7 5.2 5.0 5.2 5.4 5.1

In [ ]:
# linha 1, coluna 2
mtcars[1,2]
mtcars["Fiat 128", "cyl"]

In [ ]:
# coluna
mtcars[1]

                    mpg
Mazda RX4           21.0
Mazda RX4 Wag       21.0
Datsun 710          22.8
Hornet 4 Drive      21.4
Hornet Sportabout   18.7
Valiant             18.1
Duster 360          14.3
Merc 240D           24.4
Merc 230            22.8
Merc 280            19.2
Merc 280C           17.8
Merc 450SE          16.4
Merc 450SL          17.3
Merc 450SLC         15.2
Cadillac Fleetwood  10.4
Lincoln Continental 10.4
Chrysler Imperial   14.7
Fiat 128            32.4
Honda Civic         30.4
Toyota Corolla      33.9
Toyota Corona       21.5
Dodge Challenger    15.5
AMC Javelin         15.2
Camaro Z28          13.3
Pontiac Firebird    19.2
Fiat X1-9           27.3
Porsche 914-2       26.0
Lotus Europa        30.4
Ford Pantera L      15.8
Ferrari Dino        19.7
Maserati Bora       15.0
Volvo 142E          21.4

In [ ]:
# linha
mtcars[1,]

          mpg cyl disp hp  drat wt   qsec  vs am gear carb
Mazda RX4 21  6   160  110 3.9  2.62 16.46 0  1  4    4

In [ ]:
rownames(mtcars[7,5])
colnames(mtcars[5])

NULL

[1] "drat"

In [ ]:
mtcars[1,2]

[1] 6

In [ ]:
mtcars[c(1,2)]

                    mpg  cyl
Mazda RX4           21.0 6
Mazda RX4 Wag       21.0 6
Datsun 710          22.8 4
Hornet 4 Drive      21.4 6
Hornet Sportabout   18.7 8
Valiant             18.1 6
Duster 360          14.3 8
Merc 240D           24.4 4
Merc 230            22.8 4
Merc 280            19.2 6
Merc 280C           17.8 6
Merc 450SE          16.4 8
Merc 450SL          17.3 8
Merc 450SLC         15.2 8
Cadillac Fleetwood  10.4 8
Lincoln Continental 10.4 8
Chrysler Imperial   14.7 8
Fiat 128            32.4 4
Honda Civic         30.4 4
Toyota Corolla      33.9 4
Toyota Corona       21.5 4
Dodge Challenger    15.5 8
AMC Javelin         15.2 8
Camaro Z28          13.3 8
Pontiac Firebird    19.2 8
Fiat X1-9           27.3 4
Porsche 914-2       26.0 4
Lotus Europa        30.4 4
Ford Pantera L      15.8 8
Ferrari Dino        19.7 6
Maserati Bora       15.0 8
Volvo 142E          21.4 4

In [ ]:
mtcars[1:3]

                    mpg  cyl disp
Mazda RX4           21.0 6   160.0
Mazda RX4 Wag       21.0 6   160.0
Datsun 710          22.8 4   108.0
Hornet 4 Drive      21.4 6   258.0
Hornet Sportabout   18.7 8   360.0
Valiant             18.1 6   225.0
Duster 360          14.3 8   360.0
Merc 240D           24.4 4   146.7
Merc 230            22.8 4   140.8
Merc 280            19.2 6   167.6
Merc 280C           17.8 6   167.6
Merc 450SE          16.4 8   275.8
Merc 450SL          17.3 8   275.8
Merc 450SLC         15.2 8   275.8
Cadillac Fleetwood  10.4 8   472.0
Lincoln Continental 10.4 8   460.0
Chrysler Imperial   14.7 8   440.0
Fiat 128            32.4 4    78.7
Honda Civic         30.4 4    75.7
Toyota Corolla      33.9 4    71.1
Toyota Corona       21.5 4   120.1
Dodge Challenger    15.5 8   318.0
AMC Javelin         15.2 8   304.0
Camaro Z28          13.3 8   350.0
Pontiac Firebird    19.2 8   400.0
Fiat X1-9           27.3 4    79.0
Porsche 914-2       26.0 4   120.3
Lotus Europa        30.4 4    95.1
Ford Pantera L      15.8 8   351.0
Ferrari Dino        19.7 6   145.0
Maserati Bora       15.0 8   301.0
Volvo 142E          21.4 4   121.0

In [ ]:
mtcars[1:3,1:4]

              mpg  cyl disp hp
Mazda RX4     21.0 6   160  110
Mazda RX4 Wag 21.0 6   160  110
Datsun 710    22.8 4   108   93

In [ ]:
mtcars[1:4,]

               mpg  cyl disp hp  drat wt    qsec  vs am gear carb
Mazda RX4      21.0 6   160  110 3.90 2.620 16.46 0  1  4    4
Mazda RX4 Wag  21.0 6   160  110 3.90 2.875 17.02 0  1  4    4
Datsun 710     22.8 4   108   93 3.85 2.320 18.61 1  1  4    1
Hornet 4 Drive 21.4 6   258  110 3.08 3.215 19.44 1  0  3    1

In [ ]:
mtcars$cyl

 [1] 6 6 4 6 8 6 8 4 4 6 6 8 8 8 8 8 8 4 4 4 4 8 8 8 8 4 4 4 8 6 8 4

In [ ]:
mtcars$cyl == 4

 [1] FALSE FALSE  TRUE FALSE FALSE FALSE FALSE  TRUE  TRUE FALSE FALSE FALSE
[13] FALSE FALSE FALSE FALSE FALSE  TRUE  TRUE  TRUE  TRUE FALSE FALSE FALSE
[25] FALSE  TRUE  TRUE  TRUE FALSE FALSE FALSE  TRUE

In [ ]:
# quantos tem 4 cílindros
sum(mtcars$cyl == 4)

[1] 11

In [ ]:
mtcars[mtcars$cyl == 4,]

               mpg  cyl disp  hp  drat wt    qsec  vs am gear carb
Datsun 710     22.8 4   108.0  93 3.85 2.320 18.61 1  1  4    1
Merc 240D      24.4 4   146.7  62 3.69 3.190 20.00 1  0  4    2
Merc 230       22.8 4   140.8  95 3.92 3.150 22.90 1  0  4    2
Fiat 128       32.4 4    78.7  66 4.08 2.200 19.47 1  1  4    1
Honda Civic    30.4 4    75.7  52 4.93 1.615 18.52 1  1  4    2
Toyota Corolla 33.9 4    71.1  65 4.22 1.835 19.90 1  1  4    1
Toyota Corona  21.5 4   120.1  97 3.70 2.465 20.01 1  0  3    1
Fiat X1-9      27.3 4    79.0  66 4.08 1.935 18.90 1  1  4    1
Porsche 914-2  26.0 4   120.3  91 4.43 2.140 16.70 0  1  5    2
Lotus Europa   30.4 4    95.1 113 3.77 1.513 16.90 1  1  5    2
Volvo 142E     21.4 4   121.0 109 4.11 2.780 18.60 1  1  4    2

In [ ]:
mtcars[mtcars$cyl == 4,-2]

               mpg  disp  hp  drat wt    qsec  vs am gear carb
Datsun 710     22.8 108.0  93 3.85 2.320 18.61 1  1  4    1
Merc 240D      24.4 146.7  62 3.69 3.190 20.00 1  0  4    2
Merc 230       22.8 140.8  95 3.92 3.150 22.90 1  0  4    2
Fiat 128       32.4  78.7  66 4.08 2.200 19.47 1  1  4    1
Honda Civic    30.4  75.7  52 4.93 1.615 18.52 1  1  4    2
Toyota Corolla 33.9  71.1  65 4.22 1.835 19.90 1  1  4    1
Toyota Corona  21.5 120.1  97 3.70 2.465 20.01 1  0  3    1
Fiat X1-9      27.3  79.0  66 4.08 1.935 18.90 1  1  4    1
Porsche 914-2  26.0 120.3  91 4.43 2.140 16.70 0  1  5    2
Lotus Europa   30.4  95.1 113 3.77 1.513 16.90 1  1  5    2
Volvo 142E     21.4 121.0 109 4.11 2.780 18.60 1  1  4    2

In [ ]:
mtcars[mtcars$mpg > 20, ]

               mpg  cyl disp  hp  drat wt    qsec  vs am gear carb
Mazda RX4      21.0 6   160.0 110 3.90 2.620 16.46 0  1  4    4
Mazda RX4 Wag  21.0 6   160.0 110 3.90 2.875 17.02 0  1  4    4
Datsun 710     22.8 4   108.0  93 3.85 2.320 18.61 1  1  4    1
Hornet 4 Drive 21.4 6   258.0 110 3.08 3.215 19.44 1  0  3    1
Merc 240D      24.4 4   146.7  62 3.69 3.190 20.00 1  0  4    2
Merc 230       22.8 4   140.8  95 3.92 3.150 22.90 1  0  4    2
Fiat 128       32.4 4    78.7  66 4.08 2.200 19.47 1  1  4    1
Honda Civic    30.4 4    75.7  52 4.93 1.615 18.52 1  1  4    2
Toyota Corolla 33.9 4    71.1  65 4.22 1.835 19.90 1  1  4    1
Toyota Corona  21.5 4   120.1  97 3.70 2.465 20.01 1  0  3    1
Fiat X1-9      27.3 4    79.0  66 4.08 1.935 18.90 1  1  4    1
Porsche 914-2  26.0 4   120.3  91 4.43 2.140 16.70 0  1  5    2
Lotus Europa   30.4 4    95.1 113 3.77 1.513 16.90 1  1  5    2
Volvo 142E     21.4 4   121.0 109 4.11 2.780 18.60 1  1  4    2

In [ ]:
mtcars[mtcars$mpg > 20, c("mpg", "cyl") ]

               mpg  cyl
Mazda RX4      21.0 6
Mazda RX4 Wag  21.0 6
Datsun 710     22.8 4
Hornet 4 Drive 21.4 6
Merc 240D      24.4 4
Merc 230       22.8 4
Fiat 128       32.4 4
Honda Civic    30.4 4
Toyota Corolla 33.9 4
Toyota Corona  21.5 4
Fiat X1-9      27.3 4
Porsche 914-2  26.0 4
Lotus Europa   30.4 4
Volvo 142E     21.4 4

In [ ]:
mtcars[mtcars$cyl == 4, & mtcars$mpg > 20,]

ERROR: Error in parse(text = x, srcfile = src): <text>:1:25: unexpected '&'
1: mtcars[mtcars$cyl == 4, &
                            ^