In [ ]:
mtcars

                    mpg  cyl disp  hp  drat wt    qsec  vs am gear carb
Mazda RX4           21.0 6   160.0 110 3.90 2.620 16.46 0  1  4    4
Mazda RX4 Wag       21.0 6   160.0 110 3.90 2.875 17.02 0  1  4    4
Datsun 710          22.8 4   108.0  93 3.85 2.320 18.61 1  1  4    1
Hornet 4 Drive      21.4 6   258.0 110 3.08 3.215 19.44 1  0  3    1
Hornet Sportabout   18.7 8   360.0 175 3.15 3.440 17.02 0  0  3    2
Valiant             18.1 6   225.0 105 2.76 3.460 20.22 1  0  3    1
Duster 360          14.3 8   360.0 245 3.21 3.570 15.84 0  0  3    4
Merc 240D           24.4 4   146.7  62 3.69 3.190 20.00 1  0  4    2
Merc 230            22.8 4   140.8  95 3.92 3.150 22.90 1  0  4    2
Merc 280            19.2 6   167.6 123 3.92 3.440 18.30 1  0  4    4
Merc 280C           17.8 6   167.6 123 3.92 3.440 18.90 1  0  4    4
Merc 450SE          16.4 8   275.8 180 3.07 4.070 17.40 0  0  3    3
Merc 450SL          17.3 8   275.8 180 3.07 3.730 17.60 0  0  3    3
Merc 450SLC         15.2 8   275.8 180 3.07 3.780 18.00 0  0  3    3
Cadillac Fleetwood  10.4 8   472.0 205 2.93 5.250 17.98 0  0  3    4
Lincoln Continental 10.4 8   460.0 215 3.00 5.424 17.82 0  0  3    4
Chrysler Imperial   14.7 8   440.0 230 3.23 5.345 17.42 0  0  3    4
Fiat 128            32.4 4    78.7  66 4.08 2.200 19.47 1  1  4    1
Honda Civic         30.4 4    75.7  52 4.93 1.615 18.52 1  1  4    2
Toyota Corolla      33.9 4    71.1  65 4.22 1.835 19.90 1  1  4    1
Toyota Corona       21.5 4   120.1  97 3.70 2.465 20.01 1  0  3    1
Dodge Challenger    15.5 8   318.0 150 2.76 3.520 16.87 0  0  3    2
AMC Javelin         15.2 8   304.0 150 3.15 3.435 17.30 0  0  3    2
Camaro Z28          13.3 8   350.0 245 3.73 3.840 15.41 0  0  3    4
Pontiac Firebird    19.2 8   400.0 175 3.08 3.845 17.05 0  0  3    2
Fiat X1-9           27.3 4    79.0  66 4.08 1.935 18.90 1  1  4    1
Porsche 914-2       26.0 4   120.3  91 4.43 2.140 16.70 0  1  5    2
Lotus Europa        30.4 4    95.1 113 3.77 1.513 16.90 1  1  5    2
Ford Pantera L      15.8 8   351.0 264 4.22 3.170 14.50 0  1  5    4
Ferrari Dino        19.7 6   145.0 175 3.62 2.770 15.50 0  1  5    6
Maserati Bora       15.0 8   301.0 335 3.54 3.570 14.60 0  1  5    8
Volvo 142E          21.4 4   121.0 109 4.11 2.780 18.60 1  1  4    2

Experimente os seguintes comandos e veja quais dão um vetor com a coluna mpg do mtcars.

a) mtcars$mpg

b) mtcars[ , 3]

c) mtcars("mpg")

d) mtcars[ , "mpg"]

e) mtcars.mpg

f) mtcars[ , 1]

g) mtcars[1, 1]

h) mpg$mtcars

In [ ]:
mtcars$mpg

 [1] 21.0 21.0 22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2 17.8 16.4 17.3 15.2 10.4
[16] 10.4 14.7 32.4 30.4 33.9 21.5 15.5 15.2 13.3 19.2 27.3 26.0 30.4 15.8 19.7
[31] 15.0 21.4

In [ ]:
class(mtcars)

[1] "data.frame"

In [ ]:
mtcars[, 3]

 [1] 160.0 160.0 108.0 258.0 360.0 225.0 360.0 146.7 140.8 167.6 167.6 275.8
[13] 275.8 275.8 472.0 460.0 440.0  78.7  75.7  71.1 120.1 318.0 304.0 350.0
[25] 400.0  79.0 120.3  95.1 351.0 145.0 301.0 121.0

Achará que é função

In [ ]:
mtcars("mpg")

ERROR: Error in mtcars("mpg"): could not find function "mtcars"

In [ ]:
mtcars["mpg"]

                    mpg
Mazda RX4           21.0
Mazda RX4 Wag       21.0
Datsun 710          22.8
Hornet 4 Drive      21.4
Hornet Sportabout   18.7
Valiant             18.1
Duster 360          14.3
Merc 240D           24.4
Merc 230            22.8
Merc 280            19.2
Merc 280C           17.8
Merc 450SE          16.4
Merc 450SL          17.3
Merc 450SLC         15.2
Cadillac Fleetwood  10.4
Lincoln Continental 10.4
Chrysler Imperial   14.7
Fiat 128            32.4
Honda Civic         30.4
Toyota Corolla      33.9
Toyota Corona       21.5
Dodge Challenger    15.5
AMC Javelin         15.2
Camaro Z28          13.3
Pontiac Firebird    19.2
Fiat X1-9           27.3
Porsche 914-2       26.0
Lotus Europa        30.4
Ford Pantera L      15.8
Ferrari Dino        19.7
Maserati Bora       15.0
Volvo 142E          21.4

In [ ]:
mtcars[,"mpg"]

 [1] 21.0 21.0 22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2 17.8 16.4 17.3 15.2 10.4
[16] 10.4 14.7 32.4 30.4 33.9 21.5 15.5 15.2 13.3 19.2 27.3 26.0 30.4 15.8 19.7
[31] 15.0 21.4

In [ ]:
mtcars.mpg

ERROR: Error in eval(expr, envir, enclos): object 'mtcars.mpg' not found

In [ ]:
mtcars[, 1]

 [1] 21.0 21.0 22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2 17.8 16.4 17.3 15.2 10.4
[16] 10.4 14.7 32.4 30.4 33.9 21.5 15.5 15.2 13.3 19.2 27.3 26.0 30.4 15.8 19.7
[31] 15.0 21.4

In [ ]:
mtcars[1, 1]

[1] 21

In [ ]:
mpg$mtcars

ERROR: Error in eval(expr, envir, enclos): object 'mpg' not found

str() mostra as variáveis

In [ ]:
str(iris)

'data.frame':	150 obs. of  5 variables:
 $ Sepal.Length: num  5.1 4.9 4.7 4.6 5 5.4 4.6 5 4.4 4.9 ...
 $ Sepal.Width : num  3.5 3 3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 ...
 $ Petal.Length: num  1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 ...
 $ Petal.Width : num  0.2 0.2 0.2 0.2 0.2 0.4 0.3 0.2 0.2 0.1 ...
 $ Species     : Factor w/ 3 levels "setosa","versicolor",..: 1 1 1 1 1 1 1 1 1 1 ...

names() nomes das colunas

In [ ]:
names(mtcars)

 [1] "mpg"  "cyl"  "disp" "hp"   "drat" "wt"   "qsec" "vs"   "am"   "gear"
[11] "carb"

In [ ]:
airquality

    Ozone Solar.R Wind Temp Month Day
1    41   190      7.4 67   5      1
2    36   118      8.0 72   5      2
3    12   149     12.6 74   5      3
4    18   313     11.5 62   5      4
5    NA    NA     14.3 56   5      5
6    28    NA     14.9 66   5      6
7    23   299      8.6 65   5      7
8    19    99     13.8 59   5      8
9     8    19     20.1 61   5      9
10   NA   194      8.6 69   5     10
11    7    NA      6.9 74   5     11
12   16   256      9.7 69   5     12
13   11   290      9.2 66   5     13
14   14   274     10.9 68   5     14
15   18    65     13.2 58   5     15
16   14   334     11.5 64   5     16
17   34   307     12.0 66   5     17
18    6    78     18.4 57   5     18
19   30   322     11.5 68   5     19
20   11    44      9.7 62   5     20
21    1     8      9.7 59   5     21
22   11   320     16.6 73   5     22
23    4    25      9.7 61   5     23
24   32    92     12.0 61   5     24
25   NA    66     16.6 57   5     25
26   NA   266     14.9 58   5     26
27   NA    NA      8.0 57   5     27
28   23    13     12.0 67   5     28
29   45   252     14.9 81   5     29
30  115   223      5.7 79   5     30
⋮   ⋮     ⋮       ⋮    ⋮    ⋮     ⋮
124 96    167      6.9 91   9      1
125 78    197      5.1 92   9      2
126 73    183      2.8 93   9      3
127 91    189      4.6 93   9      4
128 47     95      7.4 87   9      5
129 32     92     15.5 84   9      6
130 20    252     10.9 80   9      7
131 23    220     10.3 78   9      8
132 21    230     10.9 75   9      9
133 24    259      9.7 73   9     10
134 44    236     14.9 81   9     11
135 21    259     15.5 76   9     12
136 28    238      6.3 77   9     13
137  9     24     10.9 71   9     14
138 13    112     11.5 71   9     15
139 46    237      6.9 78   9     16
140 18    224     13.8 67   9     17
141 13     27     10.3 76   9     18
142 24    238     10.3 68   9     19
143 16    201      8.0 82   9     20
144 13    238     12.6 64   9     21
145 23     14      9.2 71   9     22
146 36    139     10.3 81   9     23
147  7     49     10.3 69   9     24
148 14     20     16.6 63   9     25
149 30    193      6.9 70   9     26
150 NA    145     13.2 77   9     27
151 14    191     14.3 75   9     28
152 18    131      8.0 76   9     29
153 20    223     11.5 68   9     30

Funções para data frames

head(): seis primeiras linhas

tail(): seis últimas linhas (bom para ver se os últimos dados entraram no data frame)

dim(): número de linhas e colunas

names(): nomes das variáveis (colunas)

str(): estrutura do data frame

cbind(): junta tabelas lado a lado (c = column)

rbind(): junta tabelas uma sobre a outra (r = row)

Mais um data frame que vem com o R: airquality.

a) Quantas linhas e colunas tem?

b) Use a função head() nele. O que essa função faz?

c) Encontre os nomes das colunas.

d) Qual é a classe da coluna Ozone?

dim() as dimenções do DATA FRAME 153X6

In [ ]:
dim(airquality)

[1] 153   6

In [ ]:
head(airquality)

  Ozone Solar.R Wind Temp Month Day
1 41    190      7.4 67   5     1
2 36    118      8.0 72   5     2
3 12    149     12.6 74   5     3
4 18    313     11.5 62   5     4
5 NA     NA     14.3 56   5     5
6 28     NA     14.9 66   5     6

In [ ]:
head(airquality, 10)

   Ozone Solar.R Wind Temp Month Day
1  41    190      7.4 67   5      1
2  36    118      8.0 72   5      2
3  12    149     12.6 74   5      3
4  18    313     11.5 62   5      4
5  NA     NA     14.3 56   5      5
6  28     NA     14.9 66   5      6
7  23    299      8.6 65   5      7
8  19     99     13.8 59   5      8
9   8     19     20.1 61   5      9
10 NA    194      8.6 69   5     10

Dados atualizados periodicamente, melhor usar tail()

In [ ]:
tail(airquality)

    Ozone Solar.R Wind Temp Month Day
148 14     20     16.6 63   9     25
149 30    193      6.9 70   9     26
150 NA    145     13.2 77   9     27
151 14    191     14.3 75   9     28
152 18    131      8.0 76   9     29
153 20    223     11.5 68   9     30

In [ ]:
names(airquality)

[1] "Ozone"   "Solar.R" "Wind"    "Temp"    "Month"   "Day"

In [ ]:
class(airquality)

[1] "data.frame"

In [ ]:
class(airquality$Ozone)

[1] "integer"

Ainda sobre o data frame airquality: NA(não disponível) "not available":

a) Quantos NAs tem a coluna Solar.R?

b) Exiba as linhas em que Solar.R é NA.

c) Exiba as linhas em que Solar.R não é NA.

In [ ]:
dados.com.NA = c(NA,1,2,4,NA)
dados.com.NA
dados.com.NA == NA

[1] NA  1  2  4 NA

[1] NA NA NA NA NA

is.na --> colocar TRUE para NA, FALSE para outros

In [ ]:
is.na(dados.com.NA)
sum(is.na(dados.com.NA))
#sum(is.na(dados.com.NA))

[1]  TRUE FALSE FALSE FALSE  TRUE

[1] 2

In [ ]:
airquality$Solar.R

  [1] 190 118 149 313  NA  NA 299  99  19 194  NA 256 290 274  65 334 307  78
 [19] 322  44   8 320  25  92  66 266  NA  13 252 223 279 286 287 242 186 220
 [37] 264 127 273 291 323 259 250 148 332 322 191 284  37 120 137 150  59  91
 [55] 250 135 127  47  98  31 138 269 248 236 101 175 314 276 267 272 175 139
 [73] 264 175 291  48 260 274 285 187 220   7 258 295 294 223  81  82 213 275
 [91] 253 254  83  24  77  NA  NA  NA 255 229 207 222 137 192 273 157  64  71
[109]  51 115 244 190 259  36 255 212 238 215 153 203 225 237 188 167 197 183
[127] 189  95  92 252 220 230 259 236 259 238  24 112 237 224  27 238 201 238
[145]  14 139  49  20 193 145 191 131 223

In [ ]:
is.na(airquality$Solar.R)

  [1] FALSE FALSE FALSE FALSE  TRUE  TRUE FALSE FALSE FALSE FALSE  TRUE FALSE
 [13] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [25] FALSE FALSE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [37] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [49] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [61] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [73] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [85] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE
 [97]  TRUE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[109] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[121] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[133] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[145] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE

In [ ]:
sum(is.na(airquality$Solar.R))
#quantos NAs tem

[1] 7

In [ ]:
airquality[!is.na(airquality$Solar.R),]

    Ozone Solar.R Wind Temp Month Day
1    41   190      7.4 67   5      1
2    36   118      8.0 72   5      2
3    12   149     12.6 74   5      3
4    18   313     11.5 62   5      4
7    23   299      8.6 65   5      7
8    19    99     13.8 59   5      8
9     8    19     20.1 61   5      9
10   NA   194      8.6 69   5     10
12   16   256      9.7 69   5     12
13   11   290      9.2 66   5     13
14   14   274     10.9 68   5     14
15   18    65     13.2 58   5     15
16   14   334     11.5 64   5     16
17   34   307     12.0 66   5     17
18    6    78     18.4 57   5     18
19   30   322     11.5 68   5     19
20   11    44      9.7 62   5     20
21    1     8      9.7 59   5     21
22   11   320     16.6 73   5     22
23    4    25      9.7 61   5     23
24   32    92     12.0 61   5     24
25   NA    66     16.6 57   5     25
26   NA   266     14.9 58   5     26
28   23    13     12.0 67   5     28
29   45   252     14.9 81   5     29
30  115   223      5.7 79   5     30
31   37   279      7.4 76   5     31
32   NA   286      8.6 78   6      1
33   NA   287      9.7 74   6      2
34   NA   242     16.1 67   6      3
⋮   ⋮     ⋮       ⋮    ⋮    ⋮     ⋮
124 96    167      6.9 91   9      1
125 78    197      5.1 92   9      2
126 73    183      2.8 93   9      3
127 91    189      4.6 93   9      4
128 47     95      7.4 87   9      5
129 32     92     15.5 84   9      6
130 20    252     10.9 80   9      7
131 23    220     10.3 78   9      8
132 21    230     10.9 75   9      9
133 24    259      9.7 73   9     10
134 44    236     14.9 81   9     11
135 21    259     15.5 76   9     12
136 28    238      6.3 77   9     13
137  9     24     10.9 71   9     14
138 13    112     11.5 71   9     15
139 46    237      6.9 78   9     16
140 18    224     13.8 67   9     17
141 13     27     10.3 76   9     18
142 24    238     10.3 68   9     19
143 16    201      8.0 82   9     20
144 13    238     12.6 64   9     21
145 23     14      9.2 71   9     22
146 36    139     10.3 81   9     23
147  7     49     10.3 69   9     24
148 14     20     16.6 63   9     25
149 30    193      6.9 70   9     26
150 NA    145     13.2 77   9     27
151 14    191     14.3 75   9     28
152 18    131      8.0 76   9     29
153 20    223     11.5 68   9     30

In [ ]:
sum(c(1,2))

[1] 3

In [ ]:
sum(c(1,2),c(3,4))

[1] 10

In [ ]:
sum(c(1,2) + C(3,4))

ERROR: Error in `contrasts<-`(`*tmp*`, value = contr): contrasts can be applied only to factors with 2 or more levels

mean() média

In [ ]:
mean(c(1,2))

[1] 1.5

In [ ]:
mean(c(1,2),3)

[1] 1.5

In [ ]:
mean(mtcars$mpg)

[1] 20.09062

In [ ]:
mean(c(1,2,NA))

[1] NA

na.rm =    remove os NA

In [ ]:
mean(c(1,3,NA), na.rm = TRUE)

[1] 2

In [ ]:
mean(airquality$Ozone)
mean(airquality$Ozone, na.rm = TRUE)

[1] NA

[1] 42.12931

seq() função para sequências aritméticas[2+2=4+2=6]

by(razão)

In [ ]:
seq(from=4, to=10, by=2)

[1]  4  6  8 10

In [ ]:
seq(4, 10, 2)

[1]  4  6  8 10

In [ ]:
seq(by=3, to=21, from=1)

[1]  1  4  7 10 13 16 19

In [ ]:
seq(3,21,1)

 [1]  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21

# cbind(): junta tabelas lado a lado (c = column)

# rbind(): junta tabelas uma sobre a outra (r = row)

In [ ]:
tabela <- mtcars
rbind(tabela,tabela)

                     mpg  cyl disp  hp  drat wt    qsec  vs am gear carb
Mazda RX4            21.0 6   160.0 110 3.90 2.620 16.46 0  1  4    4
Mazda RX4 Wag        21.0 6   160.0 110 3.90 2.875 17.02 0  1  4    4
Datsun 710           22.8 4   108.0  93 3.85 2.320 18.61 1  1  4    1
Hornet 4 Drive       21.4 6   258.0 110 3.08 3.215 19.44 1  0  3    1
Hornet Sportabout    18.7 8   360.0 175 3.15 3.440 17.02 0  0  3    2
Valiant              18.1 6   225.0 105 2.76 3.460 20.22 1  0  3    1
Duster 360           14.3 8   360.0 245 3.21 3.570 15.84 0  0  3    4
Merc 240D            24.4 4   146.7  62 3.69 3.190 20.00 1  0  4    2
Merc 230             22.8 4   140.8  95 3.92 3.150 22.90 1  0  4    2
Merc 280             19.2 6   167.6 123 3.92 3.440 18.30 1  0  4    4
Merc 280C            17.8 6   167.6 123 3.92 3.440 18.90 1  0  4    4
Merc 450SE           16.4 8   275.8 180 3.07 4.070 17.40 0  0  3    3
Merc 450SL           17.3 8   275.8 180 3.07 3.730 17.60 0  0  3    3
Merc 450SLC          15.2 8   275.8 180 3.07 3.780 18.00 0  0  3    3
Cadillac Fleetwood   10.4 8   472.0 205 2.93 5.250 17.98 0  0  3    4
Lincoln Continental  10.4 8   460.0 215 3.00 5.424 17.82 0  0  3    4
Chrysler Imperial    14.7 8   440.0 230 3.23 5.345 17.42 0  0  3    4
Fiat 128             32.4 4    78.7  66 4.08 2.200 19.47 1  1  4    1
Honda Civic          30.4 4    75.7  52 4.93 1.615 18.52 1  1  4    2
Toyota Corolla       33.9 4    71.1  65 4.22 1.835 19.90 1  1  4    1
Toyota Corona        21.5 4   120.1  97 3.70 2.465 20.01 1  0  3    1
Dodge Challenger     15.5 8   318.0 150 2.76 3.520 16.87 0  0  3    2
AMC Javelin          15.2 8   304.0 150 3.15 3.435 17.30 0  0  3    2
Camaro Z28           13.3 8   350.0 245 3.73 3.840 15.41 0  0  3    4
Pontiac Firebird     19.2 8   400.0 175 3.08 3.845 17.05 0  0  3    2
Fiat X1-9            27.3 4    79.0  66 4.08 1.935 18.90 1  1  4    1
Porsche 914-2        26.0 4   120.3  91 4.43 2.140 16.70 0  1  5    2
Lotus Europa         30.4 4    95.1 113 3.77 1.513 16.90 1  1  5    2
Ford Pantera L       15.8 8   351.0 264 4.22 3.170 14.50 0  1  5    4
Ferrari Dino         19.7 6   145.0 175 3.62 2.770 15.50 0  1  5    6
⋮                    ⋮    ⋮   ⋮     ⋮   ⋮    ⋮     ⋮     ⋮  ⋮  ⋮    ⋮
Datsun 7101          22.8 4   108.0  93 3.85 2.320 18.61 1  1  4    1
Hornet 4 Drive1      21.4 6   258.0 110 3.08 3.215 19.44 1  0  3    1
Hornet Sportabout1   18.7 8   360.0 175 3.15 3.440 17.02 0  0  3    2
Valiant1             18.1 6   225.0 105 2.76 3.460 20.22 1  0  3    1
Duster 3601          14.3 8   360.0 245 3.21 3.570 15.84 0  0  3    4
Merc 240D1           24.4 4   146.7  62 3.69 3.190 20.00 1  0  4    2
Merc 2301            22.8 4   140.8  95 3.92 3.150 22.90 1  0  4    2
Merc 2801            19.2 6   167.6 123 3.92 3.440 18.30 1  0  4    4
Merc 280C1           17.8 6   167.6 123 3.92 3.440 18.90 1  0  4    4
Merc 450SE1          16.4 8   275.8 180 3.07 4.070 17.40 0  0  3    3
Merc 450SL1          17.3 8   275.8 180 3.07 3.730 17.60 0  0  3    3
Merc 450SLC1         15.2 8   275.8 180 3.07 3.780 18.00 0  0  3    3
Cadillac Fleetwood1  10.4 8   472.0 205 2.93 5.250 17.98 0  0  3    4
Lincoln Continental1 10.4 8   460.0 215 3.00 5.424 17.82 0  0  3    4
Chrysler Imperial1   14.7 8   440.0 230 3.23 5.345 17.42 0  0  3    4
Fiat 1281            32.4 4    78.7  66 4.08 2.200 19.47 1  1  4    1
Honda Civic1         30.4 4    75.7  52 4.93 1.615 18.52 1  1  4    2
Toyota Corolla1      33.9 4    71.1  65 4.22 1.835 19.90 1  1  4    1
Toyota Corona1       21.5 4   120.1  97 3.70 2.465 20.01 1  0  3    1
Dodge Challenger1    15.5 8   318.0 150 2.76 3.520 16.87 0  0  3    2
AMC Javelin1         15.2 8   304.0 150 3.15 3.435 17.30 0  0  3    2
Camaro Z281          13.3 8   350.0 245 3.73 3.840 15.41 0  0  3    4
Pontiac Firebird1    19.2 8   400.0 175 3.08 3.845 17.05 0  0  3    2
Fiat X1-91           27.3 4    79.0  66 4.08 1.935 18.90 1  1  4    1
Porsche 914-21       26.0 4   120.3  91 4.43 2.140 16.70 0  1  5    2
Lotus Europa1        30.4 4    95.1 113 3.77 1.513 16.90 1  1  5    2
Ford Pantera L1      15.8 8   351.0 264 4.22 3.170 14.50 0  1  5    4
Ferrari Dino1        19.7 6   145.0 175 3.62 2.770 15.50 0  1  5    6
Maserati Bora1       15.0 8   301.0 335 3.54 3.570 14.60 0  1  5    8
Volvo 142E1          21.4 4   121.0 109 4.11 2.780 18.60 1  1  4    2

In [ ]:
tabela2 <- iris
cbind(tabela2, tabela2)

    Sepal.Length Sepal.Width Petal.Length Petal.Width Species   Sepal.Length
1   5.1          3.5         1.4          0.2         setosa    5.1
2   4.9          3.0         1.4          0.2         setosa    4.9
3   4.7          3.2         1.3          0.2         setosa    4.7
4   4.6          3.1         1.5          0.2         setosa    4.6
5   5.0          3.6         1.4          0.2         setosa    5.0
6   5.4          3.9         1.7          0.4         setosa    5.4
7   4.6          3.4         1.4          0.3         setosa    4.6
8   5.0          3.4         1.5          0.2         setosa    5.0
9   4.4          2.9         1.4          0.2         setosa    4.4
10  4.9          3.1         1.5          0.1         setosa    4.9
11  5.4          3.7         1.5          0.2         setosa    5.4
12  4.8          3.4         1.6          0.2         setosa    4.8
13  4.8          3.0         1.4          0.1         setosa    4.8
14  4.3          3.0         1.1          0.1         setosa    4.3
15  5.8          4.0         1.2          0.2         setosa    5.8
16  5.7          4.4         1.5          0.4         setosa    5.7
17  5.4          3.9         1.3          0.4         setosa    5.4
18  5.1          3.5         1.4          0.3         setosa    5.1
19  5.7          3.8         1.7          0.3         setosa    5.7
20  5.1          3.8         1.5          0.3         setosa    5.1
21  5.4          3.4         1.7          0.2         setosa    5.4
22  5.1          3.7         1.5          0.4         setosa    5.1
23  4.6          3.6         1.0          0.2         setosa    4.6
24  5.1          3.3         1.7          0.5         setosa    5.1
25  4.8          3.4         1.9          0.2         setosa    4.8
26  5.0          3.0         1.6          0.2         setosa    5.0
27  5.0          3.4         1.6          0.4         setosa    5.0
28  5.2          3.5         1.5          0.2         setosa    5.2
29  5.2          3.4         1.4          0.2         setosa    5.2
30  4.7          3.2         1.6          0.2         setosa    4.7
⋮   ⋮            ⋮           ⋮            ⋮           ⋮         ⋮
121 6.9          3.2         5.7          2.3         virginica 6.9
122 5.6          2.8         4.9          2.0         virginica 5.6
123 7.7          2.8         6.7          2.0         virginica 7.7
124 6.3          2.7         4.9          1.8         virginica 6.3
125 6.7          3.3         5.7          2.1         virginica 6.7
126 7.2          3.2         6.0          1.8         virginica 7.2
127 6.2          2.8         4.8          1.8         virginica 6.2
128 6.1          3.0         4.9          1.8         virginica 6.1
129 6.4          2.8         5.6          2.1         virginica 6.4
130 7.2          3.0         5.8          1.6         virginica 7.2
131 7.4          2.8         6.1          1.9         virginica 7.4
132 7.9          3.8         6.4          2.0         virginica 7.9
133 6.4          2.8         5.6          2.2         virginica 6.4
134 6.3          2.8         5.1          1.5         virginica 6.3
135 6.1          2.6         5.6          1.4         virginica 6.1
136 7.7          3.0         6.1          2.3         virginica 7.7
137 6.3          3.4         5.6          2.4         virginica 6.3
138 6.4          3.1         5.5          1.8         virginica 6.4
139 6.0          3.0         4.8          1.8         virginica 6.0
140 6.9          3.1         5.4          2.1         virginica 6.9
141 6.7          3.1         5.6          2.4         virginica 6.7
142 6.9          3.1         5.1          2.3         virginica 6.9
143 5.8          2.7         5.1          1.9         virginica 5.8
144 6.8          3.2         5.9          2.3         virginica 6.8
145 6.7          3.3         5.7          2.5         virginica 6.7
146 6.7          3.0         5.2          2.3         virginica 6.7
147 6.3          2.5         5.0          1.9         virginica 6.3
148 6.5          3.0         5.2          2.0         virginica 6.5
149 6.2          3.4         5.4          2.3         virginica 6.2
150 5.9          3.0         5.1          1.8         virginica 5.9
    Sepal.Width Petal.Length Petal.Width Species
1   3.5         1.4          0.2         setosa
2   3.0         1.4          0.2         setosa
3   3.2         1.3          0.2         setosa
4   3.1         1.5          0.2         setosa
5   3.6         1.4          0.2         setosa
6   3.9         1.7          0.4         setosa
7   3.4         1.4          0.3         setosa
8   3.4         1.5          0.2         setosa
9   2.9         1.4          0.2         setosa
10  3.1         1.5          0.1         setosa
11  3.7         1.5          0.2         setosa
12  3.4         1.6          0.2         setosa
13  3.0         1.4          0.1         setosa
14  3.0         1.1          0.1         setosa
15  4.0         1.2          0.2         setosa
16  4.4         1.5          0.4         setosa
17  3.9         1.3          0.4         setosa
18  3.5         1.4          0.3         setosa
19  3.8         1.7          0.3         setosa
20  3.8         1.5          0.3         setosa
21  3.4         1.7          0.2         setosa
22  3.7         1.5          0.4         setosa
23  3.6         1.0          0.2         setosa
24  3.3         1.7          0.5         setosa
25  3.4         1.9          0.2         setosa
26  3.0         1.6          0.2         setosa
27  3.4         1.6          0.4         setosa
28  3.5         1.5          0.2         setosa
29  3.4         1.4          0.2         setosa
30  3.2         1.6          0.2         setosa
⋮   ⋮           ⋮            ⋮           ⋮
121 3.2         5.7          2.3         virginica
122 2.8         4.9          2.0         virginica
123 2.8         6.7          2.0         virginica
124 2.7         4.9          1.8         virginica
125 3.3         5.7          2.1         virginica
126 3.2         6.0          1.8         virginica
127 2.8         4.8          1.8         virginica
128 3.0         4.9          1.8         virginica
129 2.8         5.6          2.1         virginica
130 3.0         5.8          1.6         virginica
131 2.8         6.1          1.9         virginica
132 3.8         6.4          2.0         virginica
133 2.8         5.6          2.2         virginica
134 2.8         5.1          1.5         virginica
135 2.6         5.6          1.4         virginica
136 3.0         6.1          2.3         virginica
137 3.4         5.6          2.4         virginica
138 3.1         5.5          1.8         virginica
139 3.0         4.8          1.8         virginica
140 3.1         5.4          2.1         virginica
141 3.1         5.6          2.4         virginica
142 3.1         5.1          2.3         virginica
143 2.7         5.1          1.9         virginica
144 3.2         5.9          2.3         virginica
145 3.3         5.7          2.5         virginica
146 3.0         5.2          2.3         virginica
147 2.5         5.0          1.9         virginica
148 3.0         5.2          2.0         virginica
149 3.4         5.4          2.3         virginica
150 3.0         5.1          1.8         virginica

In [ ]:
Minha_soma <- function(x, y){
soma <- x+y
soma
}

In [ ]:
Minha_soma

function(x, y){
soma <- x+y
soma
}
<bytecode: 0x5b6eab095b18>

In [ ]:
class(Minha_soma)

[1] "function"

In [ ]:
Minha_soma(2,4)

[1] 6

c(1,2) = x

c(3,4) = y

In [ ]:
Minha_soma(c(1,2),c(3,4))

[1] 4 6

In [ ]:
c(1,2) + c(3,4)

[1] 4 6

In [ ]:
minha_soma <- function(x,y){
  return(x+y)
}

In [ ]:
minha_soma(1,2)

[1] 3

In [ ]:
minha_soma(1,5,2)

ERROR: Error in minha_soma(1, 5, 2): unused argument (2)

In [ ]:
minha_soma(c(1,2),c(5,6))

[1] 6 8

In [ ]:
resultado <- minha_soma(3,7)

In [ ]:
resultado

[1] 10

# Variáveis locais e globais

O x e o y dentro de minha_soma são locais, ou seja, só existem dentro da função. Quando a função terminou de rodar, x e y somem.

In [ ]:
soma

ERROR: Error in eval(expr, envir, enclos): object 'soma' not found

In [ ]:
por_cento <- function(valor,porcem){
  return(valor*porcem/100)
}

In [ ]:
por_cento(20,1)
#20%

[1] 0.2

In [ ]:
por_cento(porcem = 1, valor = 20)

[1] 0.2

In [ ]:
por_cento(11000,20)
#220000%

[1] 2200

In [ ]:
Exponencial <- function(x,y){
  return(x^y)
}

In [ ]:
Exponencial(9,3)

[1] 729

In [ ]:
quadrado <- function(x){
  return(x*x)
}

In [ ]:
quadrado(8)

[1] 64

In [ ]:
# raiz da soma de números
Raiz <- function(x,y){
  return(sqrt(x+y))
}

In [ ]:
Raiz(2,2)

[1] 2

In [ ]:
RaizA <- function(num, num2){
  return(sqrt(num*num2))
}

In [ ]:
RaizA(2,8)

[1] 4

In [ ]:
?sample
#Amostra aleatória

In [ ]:
sample(60,6)

[1] 19 25 55 24 21  1

In [ ]:
sample(6,100, replace = TRUE)

  [1] 6 1 1 5 1 5 3 3 2 4 1 5 5 6 1 2 2 6 3 6 6 1 2 6 2 4 6 1 2 2 5 5 4 2 6 2 4
 [38] 4 6 3 3 1 2 2 5 6 5 1 6 4 1 2 4 2 2 6 5 1 3 1 2 4 1 4 3 2 2 2 4 2 4 3 3 6
 [75] 4 3 2 5 4 5 5 6 5 5 4 6 6 6 2 4 6 3 2 5 1 1 4 3 5 5

nrow() quantas linhas

ncol() quantas colunas

In [ ]:
nrow(mtcars)

[1] 32

In [ ]:
ncol(mtcars)

[1] 11

In [ ]:
sample(nrow(mtcars),1)

[1] 11

In [ ]:
sample(ncol(mtcars),2 )

[1] 3 5

In [ ]:
mtcars[11,]

          mpg  cyl disp  hp  drat wt   qsec vs am gear carb
Merc 280C 17.8 6   167.6 123 3.92 3.44 18.9 1  0  4    4